### ISSUE TITLE
Ransackで検索フォームを作る

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#100]
/admin のproductのリストをフィルタリングできるようにしたいです。 Ransackというgemを利用しましょう。

![image](https://user-images.githubusercontent.com/627817/73588096-2a4d8600-4508-11ea-816a-e4f7cc5340b0.png)

**Comment by ms2sato** [comment]
- [ ] titleの完全一致で絞り込める
- [ ] status を選択して絞り込める
- [ ] Priceの範囲で絞り込める

**Comment by shuma1020** [comment]
@ms2sato 
[こちら](https://qiita.com/nojinoji/items/e1b174220da8c81a1756)を参考にしているのですが、遷移先がadmin/productsではなく、productsになってしまうので格闘中です。
formのモデル指定に問題があるのかといじってみたのですが、なんの変化もなく、エラーも出ませんでした。この部分を変更したのに何もエラーが出ないということは少し怪しいのでもう少し格闘してみます。現状報告でした
```
 = search_form_for(model: [:admin, @q]) do |f|
```

**Comment by shuma1020** [comment]
@ms2sato 
下記のようにして解決
```
= search_form_for(@q, url:admin_products_path) do |f|
```

**Comment by shuma1020** [comment]
@ms2sato 

statusをselectタグで指定し、送信しても反映されない状態です。
下記のログからstatusの送信自体はできているが、Ransack::searchのvalueのところに組み込まれていない。つまり@q = Product.ransack(search_params)の部分がtitleのみしか受けていないと考えています。

解決案
1.　フォームを分ける。@qではないインスタンス変数を作る。
→あまりいい方法ではないと推測している。できるかもしれないが、@qに１つに複数の条件を入れるのが望ましい。
2. valuesのところにstatusを組み込む。この方法を模索中

```rb
= search_form_for(@q, url:admin_products_path) do |f|
    = f.label :title, "Keyword"
    = f.search_field :title_eq
    = f.label :statuses_id_eq, '学部'
    = f.select :status, Product.statuses.keys
    = f.submit "検索"
```

```rb
def index
        p @q = Product.ransack(search_params)
        p "dddddddd"
        p @products = @q.result(distinct: true)
    end
```
```bash
  Parameters: {"q"=>{"title_eq"=>"honda", "status"=>"draft"}, "commit"=>"検索"}
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
   (0.6ms)  SELECT COUNT(*) FROM "notifications" WHERE "notifications"."user_id" = $1 AND "notifications"."status" = $2  [["user_id", 2], ["status", 0]]
  ↳ app/controllers/application_controller.rb:9:in `notification'
Ransack::Search<class: Product, base: Grouping <conditions: [Condition <attributes: ["title"], predicate: eq, values: ["honda"]>], combinator: and>>
```

**Comment by shuma1020** [comment]
下記に変更したがうまくいかず。
```
= f.select :status, Product.statuses.to_a.map { |w| [w[0], w[1]] }
```

**Comment by shuma1020** [comment]
そもそもselectタグじゃなくて、ラジオボタン検索なんかもしれなと推測

**Comment by ms2sato** [comment]
@shuma1020 ちょいまってね。selectでも当然できるはず。 ransack では name を特殊な書き方することで合致を調べられると思うんだけど、 `f.select :status_eq` は試した？

**Comment by shuma1020** [comment]
@ms2sato 
eqつけたらできました！selectタグは選択肢が限られているので、eqなどを明示する必要はないのではないかと考えいてつけていませんでした。

**Comment by shuma1020** [comment]
メモ
```
* = (equal) : eq
* < (less than) : lt
* <= (less than equal) : lteq
* > (greater than) : gt
* >= (greater than equal) : gteq
```

**Comment by ms2sato** [comment]
@shuma1020 ransack はこの感じで formの動きを拡張するので、この辺り理解すれば敵じゃないすよ。メモってくれている内容はとてもいいね。これで色々な絞り込みを作れます。

**Comment by shuma1020** [comment]
@ms2sato 検索がかなり楽に作れるようになりました！

**Comment by ms2sato** [comment]
@shuma1020 Good、いつものことだけど「こいつはどういう仕組みで動いているんだ？」という観点で確認してみてね。

**Comment by shuma1020** [comment]
@ms2sato 
ransackメソッドにパラメーターを入れると対応するカラム、属性(ex eq,it)、入れられた値を探す。昔はsearchメソッドでしたが今はransackになっていると考えています。Ransack::searchの詳しい仕組みもちゃんと理解した方がいいですか？gemを見てみたのですが、かなり複雑でした。
```
Ransack::Search<class: Product, base: Grouping <conditions: [Condition <attributes: ["title"], predicate: eq, values: ["honda"]>
```

**Comment by ms2sato** [comment]
@shuma1020 まだ gem の中身まで見るのはハードルが高いので、以下くらいをわかってくれていると良いです。

- eq、lt などの意味（上記でまとめてくれた意味合いでOK）
- それぞれを指定した時に発行されるSQL（暗記しなくて良いが「こういうのが発行されるはず」という理解）
- もしもransackを使わなかった時に上記のSQLを発行するActiveRecordが書ける（これはちゃんと書けてほしい）。

search or ransack については理解大丈夫かと。

**Comment by shuma1020** [comment]
@ms2sato 
> もしもransackを使わなかった時に上記のSQLを発行するActiveRecordが書ける（これはちゃんと書けてほしい）。

上記のSQLを発行するActiveRecordが書けるというのは、「全く同じSQLを発行」それとも「同じ内容（＝検索して、それを出力)」すれば良いのかどちらでしょう？

**Comment by ms2sato** [comment]
@shuma1020 理想は「全く同じSQLを発行」ですが、同じ結果が絞り込まれる記述ができるならそれもありです（現在単純なデータしか扱っていないので、たまたま同じ結果が絞られる可能性はありますが、"SQLの意味"として同じになることは最低条件）。

**Comment by shuma1020** [comment]
同じ結果(title)が発行されるメソッドを作りました。全く同じSQLはまだ考えています。
```
self.where(['title like?', "#{search}"])
```

**Comment by ms2sato** [comment]
![image](https://user-images.githubusercontent.com/627817/73923028-8bf96000-490d-11ea-86f0-e8089123aa0c.png)


bootstrapのスタイルはあてましょうか。

**Comment by ms2sato** [comment]
状態の i18n 対応はしておいてくださいな。

**Comment by shuma1020** [comment]
@ms2sato 
> 理想は「全く同じSQLを発行」ですが、同じ結果が絞り込まれる記述ができるならそれもありです（現在単純なデータしか扱っていないので、たまたま同じ結果が絞られる可能性はありますが、"SQLの意味"として同じになることは最低条件）。

上記で自分が述べたものはこの回答として適切ですか？

**Comment by ms2sato** [comment]
@shuma1020 「titleの完全一致」という仕様ですね。

`self.where(['title like?', "#{search}"])` は同じ結果が絞り込まれるとは思いますが、一般的に良く使われる形ではありません。もっと簡単な記法で同じことができるので、まずそちらに思い至るべきです。

https://github.com/shuma1020/training_app/issues/100#issuecomment-581000276
にある仕様を素直に実現するActiveRecordが書ければ及第点です。求められているのは「たとえransackが無い環境でも、自分で同様の結果の絞り込みを適切に書ける」ということです。

**Comment by shuma1020** [comment]
@ms2sato 
少し苦戦しています。titleでの絞り込みはでき、パラメーターとしてstatusの値は渡せているので問題はSQLにあると考えています。
```
@products  = Product.where("title LIKE ? or status::text LIKE ? or price::text LIKE ?","%#{params[:title]}%","#{params[:status_eq]}","#{params[:price]}")
```

```
SELECT "products".* FROM "products" WHERE (title LIKE '%プログラミング%' and status::text LIKE '%release%' or price::text LIKE '') LIMIT $1 OFFSET $2  [["LIMIT", 8], ["OFFSET", 0]]
```

**Comment by ms2sato** [comment]
@shuma1020 一個ずつやりましょう。ちょっと私の意識づけが緩かったので制限入れます。

以下のようにそれぞれ一つずつこなしてください。課題を分割するイメージです。

### 1. それぞれを "Ransackの事は忘れて" 記述する
- a. 「titleの完全一致で絞り込める」をActiveRecordで記述する
- b. 「status を選択して絞り込める」をActiveRecordで記述する
- c. 「Priceの範囲で絞り込める」をActiveRecordで記述する

シンプルな記述でa, b, c をそれぞれやる。シンプルな書き方があればそちらを使ってください。

### 2. aかつbかつcを一度に検索できるように記述する
3つの条件で絞り込めるようなロジックを書く。

### 3. aだけ、aかつb、bかつc など条件が バラバラに送られた場合に対応する
これはちょっと工夫が必要です。コードも長めになりそう。
