### ISSUE TITLE
[再挑戦]ドロップダウンの内容を i18nする

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#101]
![image](https://user-images.githubusercontent.com/627817/73588133-9334fe00-4508-11ea-880a-3f7e770a4518.png)

**Comment by shuma1020** [comment]
@ms2sato 
[こちら](https://qiita.com/tanutanu/items/d44a92425188a4489ec6)を参考にしました！

**Comment by ms2sato** [comment]
@shuma1020 参考にした内容も良いね。ちなみに以下のような書き方もあるんだけど、どういうメカニズムで動いているか推察できそう？

```
<%= f.select :visibility, Area.visibilities_i18n.invert, :class => 'form-control' %>
```

**Comment by shuma1020** [comment]
@ms2sato 
ここでいうvisibilitiyやAreaは自分の場合だとstatusとProductとであると考えてよろしいですか？キーと値を入れ替えてハッシュを返す効果が考えられます！

**Comment by ms2sato** [comment]
@shuma1020 

> visibilitiyやAreaは自分の場合だとstatusとProductとである

YES。そろそろこの辺りはわざわざ確認せずともコードを見た時に類推できて良いと思います。


リンク先のコードは配列の配列で作成しているけれど、私が提示した方はハッシュです。 f.select がどちらの型も対応していて、書き方が何通りかあります。

`Area.visibilities_i18n.invert` の書き方が一番シンプルにできると思うので理解して使えると良いでしょう。

**Comment by ms2sato** [comment]
と、思ったら治ってたのでclose
