### ISSUE TITLE
donationを設定する画面を修正する

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/training_app#102]

**Comment by shuma1020** [comment]
エラーメッセージを編集する

1.Donationとrewardを日本語に直す
<img width="694" alt="スクリーンショット 2020-02-03 20 47 03" src="https://user-images.githubusercontent.com/56459339/73650843-7514fc80-46c6-11ea-8c8b-8cca38f4263a.png">

**Comment by shuma1020** [comment]
@ms2sato 
locale/models/patron/ja.ymlを下記のようにしました。しかし日本語に変更することができませんでした。そもそもここのdonationは@patron.errorsのerrorsのことであると考え、locales/ja.ymlのerrors/messagesなどに追加しましたがうまく行きませんでした。
```rb
ja:
  activerecord:
    models:
      patron: パトロン
    attributes:
        patron:
        donation: 寄付金
```

**Comment by ms2sato** [comment]
@shuma1020 ymlファイルは 親子関係や構造をインデントで指定するフォーマットですが、今書いてあるコードは親子関係が適切に指定できているか確認してください。こういうところでうまく動かないのは凄く勿体無いので「そもそもどういうものか」を掴んでいくようにしましょう。

ちなみに、単純に綺麗に書くだけでこういうところは問題なく進んだりするので丁寧に書いとくと変な悩みが減りますよ。

**Comment by shuma1020** [comment]
@ms2sato 
承知しました！見直します！

**Comment by ms2sato** [comment]
メモ: 多分どこかで治っている。改めて確認したらマージ予定

**Comment by shuma1020** [comment]
@ms2sato 
いっときはlayoutにて下記のようにして直したと思うのですが、今見たら英語が出力されていました。yml自体は下記のままです。

```
ja:
  activerecord:
    models:
      patron: パトロン
    attributes:
        patron:
          donation: 寄付金
```
