### ISSUE TITLE
RSpecを学習する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#105]
書籍は渡したのでまず学習しましょう。
その後、このサービスのSpecを書いていきます。

まずはModelのSpecを書ける程度の知識が手に入ったら @ms2sato へ声かけください。

**Comment by shuma1020** [comment]
@ms2sato 
ブランチ切ってやろうかと思うのですが、layoutがマージされてからの方がいいですか？

**Comment by ms2sato** [comment]
@shuma1020 ブランチ切りましょう。layout でロジックをほとんどいじっていない（はず）なので、コンフリクトも大してしないと思います。

もう結構理解進んでいるんでしょうか。テスト用のデータを作成する部分は FactoryBot を導入して欲しいです。

まず Productあたりを攻めていくと学習には良いはず。

- Productのデータのバリデーションを書いてみる（これは小手調べ）
- Productのモデルに追加したモデルのメソッドについて書いてみる

ProductができたらPatronも書きましょう。

**Comment by shuma1020** [comment]
@ms2sato 
layoutのコンフリクトをしようと思う、masterをプルしたらpaginationがコンフリクトを解消してもおかしな状況になってしまいました。プルする前は正常なので、コンフリクトをlayoutの方に合わせて調整したら、正常になるはずなのですがいまいち原因が特定できません。試したことはkaminariをもう一度bundle iすることです。

RSpecはまだ２章に入ったばかりです。
<img width="674" alt="スクリーンショット 2020-02-07 19 26 33" src="https://user-images.githubusercontent.com/56459339/74021866-c7fcf580-49df-11ea-932a-d70fd1f8cf18.png">

**Comment by shuma1020** [comment]
@ms2sato 了解です！マージ待たずに切っちゃいます。まだ２章のはじめのところです。

**Comment by shuma1020** [comment]
メモ
## p40に関して
p40のUserに関するバリデーションテストが教科書と逆の結果(failures)になる。Userモデルに設定しているカラムが違うことが原因と推測。教科書ではtoの時にvalid?メソッドを呼び出しても有効にならないと書いてあるが、自分の場合to_notの時にそのことが言える。Userモデルでnameにpresence: trueのバリデーションは設定済み。
```
it "is invalid without a  name" do
    user = User.new(name: nil)
    user.valid?
    expect(user.errors[:name]).to include("can't be blank")
  end
```
> 今回は新しく作ったユーザー(first_name には明示的に nil をセットします)に対して valid? メソ ッドを呼び出すと有効(valid)に ならず 、ユーザーの first_name 属性にエラーメッセージが付いて いることを 期待(expect) します。RSpec をもう一度実行すると、二番目までのスペックがパスするは ずです。

属性にエラーメッセージがつくということは下記のようなことなのか？
```
User is invalid without a  name
     Failure/Error: expect(user.errors[:name]).to include("can't be blank")
       expected ["を入力してください"] to include "can't be blank"
     # ./spec/models/user_spec.rb:17:in `block (2 levels) in <main>'
     # -e:1:in `<main>'
```

**Comment by ms2sato** [comment]
@shuma1020 エラーメッセージをちゃんと読むんや！そこから推察できることや！

**Comment by shuma1020** [comment]
@ms2sato 
> expected ["を入力してください"] to include "can't be blank"

nilだからこのメッセージが出ていることはわかっているんですけど、教科書ではexpect(user.errors[:name]).toの時はエラーメッセージ自体出ず、to_notの時に出ると書いてあります。

**Comment by ms2sato** [comment]
@shuma1020 今のRSpecのコード、まだ良くわかっていないのに trainig_app のコードを元にして直接やろうとしていて、それで起きて当然なことを勝手に混乱しています。

@shuma1020 はちょっとした際に推察が追いつかずに混乱するタイプだから、教科書を読みながら学んでいる最中ならそんなに焦ってやらずに、それ用のプロジェクトをゼロから作って試すことを進めるよ。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！そうします！

**Comment by shuma1020** [comment]
@ms2sato 
正しいcloneの流れを確認したいです！自分は下記の流れで行いました。(既存のプロジェクトなのでgit initはいらない？)
```
ローカルで新しいプロジェクトを作成(mkdir xxxx)
そのプロジェクトに移動(cd xxxx)
git init 
git clone xxxxxxxxxxxxxxxxxxx
```

cloneした時にbundleのバージョンが合わなかったのですが、その対応として下記はあっていますでしょうか？一応使えるようにはなったのですが、これを機にちゃんとcloneして使えるようにしたいです。
バージョンが合わないことによるエラー
```
bundle -v
Traceback (most recent call last):
        2: from /Users/shuma/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
        1: from /Users/shuma/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/shuma/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```
```
1. gemfile.lockの　BUNDLED WITHを確認(例：1.14.6),bundlerのバージョンも(1.13.0)
2. gem install bundler 1.14.6
3.gem unistall bundler 1.13.0
```

**Comment by ms2sato** [comment]
@shuma1020 
> 既存のプロジェクトなのでgit initはいらない？

YESです。

bundlerはその方法で RSpecのプロジェクトは動くかもしれませんが、他のプロジェクトが失敗する可能性があります。rbenv を利用していて、Rubyのバージョンが違うものなら大丈夫でしょう。

uninstall せずに複数バージョンを入れておく形を目指して、下記のようにやるのが良いかもしれません（多分複数バージョン入っていても適切なものが選ばれると思う）
`gem install bundler -v 1.14.6`

**Comment by shuma1020** [comment]
@ms2sato 
> rbenv を利用していて、Rubyのバージョンが違うものなら大丈夫でしょう。

というのは自分のやったcloneの仕方(git initを含まない)で大丈夫ということでしょうか？bundlerのバージョンはアンインストールではなく、追加ということは理解しました！

**Comment by ms2sato** [comment]
@shuma1020 与えられた情報から、考えられることをおろそかにしないようにして欲しいです。全部を「大丈夫でしょうか？(Y/N)」とするのではなくて「自分はこうしたのだから、大丈夫だ」と考えられるようにならないといけない。そうしないと全部人に聞かないといけないし、その為の不足している情報を誰かに教えないといけないですよね。

端的に今の @shuma1020 のマシン環境を私が把握していないので答えられないというのが回答の一つです。以下のような観点で自分で考える必要があります。

- rbenv を利用していて（rbenvが何かを理解している前提で、今回のcloneで利用しているかを自分で考える必要がある。根拠があり、答えがあるはず）
- Rubyのバージョンが違う（利用しているRubyのバージョンを上記の前提の上で確認する必要がある）

**Comment by shuma1020** [comment]
@ms2sato 
> 正しいcloneの流れを確認したいです！

確認の仕方が悪かったかもしれません。
最初の質問(git cloneの流れ)に対応する返信は
> Yesです。

だと思うのですが、それは「git initは不要であること単体」に対して修飾しているのか、それとも「git initは不要かつ自分の提示した流れはあっているということ」、どちらなのかを確認したかったです。

**Comment by shuma1020** [comment]
@ms2sato 
すいません。質問を２つまとめてしていたのがよくなかったと思います。
1.git cloneの流れは自分の提示したものでいいのか？（これは確認です。ネットにやり方がいくつかのっている中で、自分がこれでいいのではないかというものです。)
```
ローカルで新しいプロジェクトを作成(mkdir xxxx)
そのプロジェクトに移動(cd xxxx)

git clone xxxxxxxxxxxxxxxxxxx
```
2.bundlerのバージョンに関して。

**Comment by ms2sato** [comment]
@shuma1020 

>> 既存のプロジェクトなのでgit initはいらない？

> YESです。

先に上記の表現で、一問一答的に答えています。引用された範囲についてYESと答えました。それ以上でも以下でも無い表現だと受け止めて良いです。

> 「git initは不要かつ自分の提示した流れはあっているということ」

これにYESと端的に答えられない、というのが私の返信です。懸念点として「他のプロジェクトが失敗する可能性があります。」という事があります。それが特に問題いと判断できる、もしくは他のプロジェクトが失敗しないなら「問題がない」です。

「合っている」というのは「正解がある」と思っているように受け止められますが、「正解」というのは前提や環境で変わるもので、IT技術を扱っている中で「これが正解」と言えることはとても少ないです。動いていれば正解と決めれば、動いていることが正解です。「他のプロジェクトも今まで通り何もしなくても動く」という事が正解ならもしかしたら不正解かもしれません。

少なくとも不具合なく動くなら「間違いではない」と言えます。 @shuma1020 の最初に書いたものが自分の想定通り不具合なく動いているなら「間違いではない」です。

**Comment by ms2sato** [comment]
@shuma1020 勘違いがないように改めて伝えておきますが

@shuma1020 が質問している「合っていますか」という言葉に私は YESともNOとも言っていません（言えません）。「もしかしたら他のプロジェクトで何か起こるかもしれないけれど、それが解決できるなら別に問題ないようには見える。」という事くらいしか言えない状況なんです。

**Comment by shuma1020** [comment]
@ms2sato 
# クローンに関して
## 自分が勘違いしていた点
- クローンする時は決まり決まったやり方が存在し、自分のやり方はどのプロジェクトに対しても通用する
## 今の理解

- クローンもその人の環境によって、そのプロジェクトの環境によって異なる。自分の提示したやり方は、今回のプロジェクトに関してだけ言えば間違いではない。ただそれは他のプロジェクトにも通用する普遍的なやり方ではない。

- 他のプロジェクトでも失敗しないやり方が他にある。

# bundlerに関して
## rbenvを利用しているかを確認する
rbenvは、複数のRubyのバージョンを管理し、プロジェクトごとにRubyのバージョンを指定して使うことを可能としてくれるツールと理解。

> rbenvを利用していて、

というのはそのプロジェクトがrubyであるかどうかということではないかと推測。

## バージョンに関して
この箇所が理解しきれていません。自分はbundlerのバージョンさえ合わせてしまえばいいものだと考えていました。
> Rubyのバージョンが違うものなら大丈夫でしょう

上記の理解はこのようになります。
- ruby -versionでそのプロジェクトのバージョンを確かめる
- インストール済みのものかどうか確かめる。
プロジェクトで用いられているrubyは自分のローカルでインストールされているかを確認

**Comment by ms2sato** [comment]
@shuma1020 ちょっと分け目が違うかもしれないので。

## git clone 
`git clone` そのものは「リポジトリにあるファイルを全部持ってきて git の準備をする」なので、そのコマンドを打ってファイルが取得でき、gitで管理されるならそれで正しいはず。この動きがプロジェクトで違うことはほぼ無い。だから私は先の質問に関して明確に YES/NO も伝えられています。

もしも上記以上の理解をしているとすれば `git clone`を過大評価し過ぎです。

## 今回失敗したこと
bundle install の為の bundlerのバージョンが違う。
これはgitの問題では無いので clone の問題では無いです。 bundler の扱いの話です（というのは理解していると感じている）。

## それ以上先のこと
これを文章で書くと長過ぎて辛いし、それで通じる気がしないので、以下のことだけは調べて次の対面で話題にしましょう。

- bundler とは何か（わかっていそうだけど確認しておいてください）
- rbenvが解決する問題。rbenvが無いと何が困るのか。

**Comment by ms2sato** [comment]
@shuma1020 で、今どうすれば？と思うかもしれませんが、 「とりあえず動く」ところまで進められていると思うので、続けてしまって良いと思います。今後問題出たらその都度解消しに行っても大丈夫だと思います。

**Comment by shuma1020** [comment]
@ms2sato git cloneと今回失敗したことの理解は @ms2sato さんと一致しているかなと思っています！rbenvが解決する問題に関してもしかしたら勘違いしているところがあると思うので、次回の対面までに整えておきます！とりあえずRSpecに関しては進めそうなのでそのまま進めます！

**Comment by shuma1020** [comment]
@ms2sato 
下記に関する理解の確認です。
```rb
RSpec.describe Project, type: :model do
  it "does not allow duplicate project names per user" do
    user = User.create(
      first_name:"Joe",
      last_name: "Tester",
      email:"joetester@example.com",
      password:"dottle-nouveau-pavilion-tights-furze",
    )

    user.projects.create(
      name: "Test Project",
    )

    new_project = user.projects.build(
      name: "Test Project",
    )

    new_project.valid?
    expect(new_project.errors[:name]).to include("has already been taken")
  end

end
```
```rb
expect(new_project.errors[:name]).to include("has already been taken")
```

「has already been takenというエラーをnew_projectのエラーが含んでいたらパスする」と下記の根拠より推測しています。

- projectの名前を重複を避けたものに変えた場合、1failureとなる。
→ valid?がtrueになり、エラーを保有しない。つまりエラー自体存在しないからエラーの中にhas already been takenは含まれない。

- include("has already been taken")の has already been takenの文字を適当な文字(例：aaa)に変更すると1failure
→　valid?がfalseの場合でも、aaaはvalidationエラーに含まれている文字と一致しない。

少し混乱するのが「予想していたエラーが出たらパスする」という点です。RSpecはそういうものだと理解しているのですが、たまに少し混乱しました。

**Comment by ms2sato** [comment]
@shuma1020 理解バッチリです。

テストは「仕様に合致しているか確認する。仕様に合致するとグリーン。」というイメージを持てる方がいいですよ。
「『xxxのエラーが発生する』という仕様をチェックしているなら、エラーが発生すればグリーン。エラーが発生しないのがレッド。」

テストにおけるレッド/グリーンは推察可能かと思いますが、わからない場合には調べてみてください。

**Comment by shuma1020** [comment]
@ms2sato 少しずつ理解できてきました！

**Comment by ms2sato** [comment]
@shuma1020 この話も奥が深いので、90分の時間内とかでミッチリ説明したりします。 今は @shuma1020 だけの90分が毎回提供できるので、次回軽く伝えられると思います。

**Comment by shuma1020** [comment]
@ms2sato ありがとうございます!
あとリモートのbranchを下記のようにcheckout し、bin/rspecをするとずっとフリーズしてしまいます。特にエラーもありません。そこで仕方なくcontroll+cを押し、途中でやめたのですがその時に出たログというのは参考にしていいものなのでしょうか？
```
git checkout -b my-04-factories origin/03-models
```
このログを見ると、springに問題があるのではないかと。
```
$ bin/rspec
                                        c       c^CTraceback (most recent call last):
        14: from bin/rspec:3:in `<main>'
        13: from bin/rspec:3:in `load'
        12: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/bin/spring:15:in `<top (required)>'
        11: from /Users/shuma/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        10: from /Users/shuma/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
         9: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
         8: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
         7: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
         6: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
         5: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
         4: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/client/run.rb:35:in `call'
         3: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/client/run.rb:42:in `warm_run'
         2: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/client/run.rb:62:in `run'
         1: from /Users/shuma/dev/rspec_tutorial/everydayrails-rspec-2017/vendor/bundle/gems/spring-2.0.1/lib/spring/client/run.rb:117:in `verify_server_version'
````

**Comment by ms2sato** [comment]
@shuma1020 そのログは途中で止まっているのであまり意味がないですね。

`bin/spring stop` するとどうですか？

**Comment by shuma1020** [comment]
@ms2sato 通りました！springというのは今回この状態になって初めて調べてみて知った単語だったので、もう少し調べてみます！

**Comment by shuma1020** [comment]
メモ
factory_botの意味があんまりピンときていない。要は「クラス内の最低限の属性についてのみ値を定義する」ということなのか？

**Comment by ms2sato** [comment]
@shuma1020 だいたい合っている。テストを書く時に create でいろんな引数をいれないといけないのが大変だから、デフォルトで当たっている引数を別途書いておけるイメージ。

**Comment by shuma1020** [comment]
@ms2sato RSpec用のプロジェクトがモデルまで一通り終わったので、sample_projectでできるかやってます！以前ひかかっていた箇所を自分で解決することができました。

```
it "is invalid without name" do

  user = User.new(name:nil)
  user.valid?
  expect(user.errors[:name]).to include("を入力してください")
end
```

**Comment by shuma1020** [comment]
@ms2sato こちらもブランチ作りました！

**Comment by ms2sato** [comment]
@shuma1020 素晴らしい！以前の問題を自力解決できたのは、あの時よりも理解が進んでいる証拠です。理解せずに焦っても適切な仕事はできないので、技術に関してはまず自分のモノにすることを考えてください。瞬殺できる事がどんどん増えるので、学習してそれを増やしてください。

ブランチ作成ありがとうございます。

**Comment by ms2sato** [comment]
@shuma1020 Issueを私にアサインしないでください。
