### ISSUE TITLE
[layoutマージ後] @current_donation 周辺のロジックを整理

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#107]
Productに、以下のメソッドを作りましょう。作ったメソッドを利用して `products#show` を修正してください。

- current_donation: 現在の募金の総額
- percent: 現在の募金とpriceの割合

モデルにはロジックが集まっている形にしたいので、Product が持つべき情報の計算は Productの中で済ませたいのです（コントローラにロジックの内訳を教えたくない）。

**Comment by shuma1020** [comment]
@ms2sato 
下記のようにしてみました！

```rb
def self.count_donation(patrons)
        patrons.sum{|patron|patron[:donation]}
    end

    def self.percent_of_donation(dontaion, product)
        (dontaion.to_f / product.price * 100).round(0)
    end
```

**Comment by ms2sato** [comment]
@shuma1020 ブランチ無いんですね。もうPRするの当たり前にこなして欲しいです。コメントしたいのでブランチしたら連絡ください。

**Comment by shuma1020** [comment]
@ms2sato 
比較的大きな変更ではなかったのでmasterで行なっていました。
