### ISSUE TITLE
[練習] CSS で の中央寄せについて調べる。いくつかのパターンを書く。

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#108]
CSSでよくやりたくなることの一つに、上下中央、左右中央、上下左右中央 などがあります。これについていくつかやり方があるので調べてみましょう。

可能ならサンプルのCSSを書けると良いので、どこかに練習用のページを作っても良いです。自分なりに「こうやったらできる」というのを何パターンか書いてください。

**Comment by shuma1020** [comment]
@ms2sato ブランチを作成しました！

**Comment by ms2sato** [comment]
一旦終わったのでCLose
