### ISSUE TITLE
Product#status のフォームからの指定で enumの情報を使ったドロップダウンにする

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#11]
日本語化（i18n）は後でやるので、一旦ドロップダウンにしてみてください。

**Comment by shuma1020** [comment]
#9でstatusを下書き、公開にしたこととはまた別ですか？

**Comment by ms2sato** [comment]
https://github.com/shuma1020/training_app/blob/master/app/views/products/_form.html.erb#L32

あぁ、なるほど。こう変更しているんですね。i18nも済んでいる様子なので、下記の情報を利用してi18n も対応したものに変更しましょう。下記のページでは具体的にselectに指定するところまで書かれていませんが、selectの動きを調べればできます。逆に適当どこかのページに書いてある内容をコピペで動かしているのではダメです。

https://kimuraysp.hatenablog.com/entry/2016/05/19/233144

**Comment by ms2sato** [comment]
残りはi18nなので、これはClose
