### ISSUE TITLE
かなり前にやった演算子式に関する確認です

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/training_app#120]
@ms2sato 
下記の式の理解は「product.userがselfとイコールではなく、かつlikesにproduct.idが存在しない、かつproductが存在する」であっていますでしょうか？一度確認したところなので、これであっていると思うのですが念のための確認です。
```
product && product.user != self && !likes.exists?(product_id: product.id)
```
[演算子式](https://docs.ruby-lang.org/ja/latest/doc/spec=2foperator.html)

**Comment by ms2sato** [comment]
@shuma1020 だいたいいいですが、

> likesにproduct.idが存在しない

この言葉の意味するところは明確には伝わっていないので表現を改められないでしょうか。

**Comment by shuma1020** [comment]
@ms2sato 
likesモデルのproduct_idカラムがproduct.idではない(イコールではない)などはいかがでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 likes はモデルでは無いので、以下のような表現だと思います。

selfに関連しているLikeモデルの中に、product_id = product.id になるものが存在しない。

**Comment by shuma1020** [comment]
@ms2sato承知しました！最初は ActiveRecord::Associations::CollectionProxyの中にと表現しようと思っていたのですが、それだと意味は通じづらいでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 

> ActiveRecord::Associations::CollectionProxyの中に

なるほど。型が明確なのはメッチャいいんだけど、会話の中だと辛いので「関連している」とかで意味を伝えてしまう方がこの手の時には多いです。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！ありがとうございます！

**Comment by ms2sato** [comment]
単純な質疑応答だと思うのでClose
