### ISSUE TITLE
[木曜]現状の疑問点・ぶつかっているところ

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/training_app#13]
先ほど新たなissueが追加されるまでにgem 'devise'を追加し、userモデルも追加したのですがユーザー権限の箇所に疑問点があります。
1.gem 'devise'はsessionの機能も含まれているのか
→含まれていると分析

rails アソシエーションに関して
product index　
<%= product.user.email %>

github上からvendor/bundleを削除しようとしたら、vs codeのvenderが赤になってしまった。

**Comment by ms2sato** [comment]
一旦溜めといていただいて、木曜に見ますかー

**Comment by ms2sato** [comment]
追加
https://github.com/shuma1020/training_app/issues/5#issuecomment-560998433
