### ISSUE TITLE
[検討] reward belongs_to user は必要か

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#14]

**Comment by shuma1020** [comment]
よく考えて見るとrewardはproductに従属していて、そのproductはuserに従属しているのでここで改めてreward belongs_to userと示す必要はないかもしれません。

**Comment by ms2sato** [comment]
@shuma1020 なるほど。だとすると適切な構造に直すことはできますか？

**Comment by shuma1020** [comment]
@ms2sato 
変更後、test　branchにpushしてみました！

**Comment by ms2sato** [comment]
@shuma1020 確認させてください。このブランチでやろうとしていた変更は test ブランチに含まれている、という理解で合っていますか？ test ブランチは破棄しようと思ってたけどしない方がいいですよね？

**Comment by shuma1020** [comment]
削除してもらって構いません！masterに本件に当たる変更を載せました。二度手間になり申し訳ありません。何卒よろしくお願いします！

**Comment by ms2sato** [comment]
@shuma1020 承知ー。そしたら続きで、 `test` ブランチをPullRequest してみてください（これも練習です）

**Comment by ms2sato** [comment]
@shuma1020 

https://github.com/shuma1020/training_app/blob/master/db/schema.rb#L39
user_id が残ってしまっていますね。 消すマイグレーションをやってみましょう。練習なので、ちゃんとやって大丈夫です（色々と迂回する手もあるんですが、今は真っ当にマイグレーションで消しましょう。

基本的に何かやったことを戻す方法はそれぞれ用意されているので、元通りになったかはチェックできると良いですね！

**Comment by shuma1020** [comment]
@ms2sato 
今考えられたやり方は二つで当たらなmigrationファイルを作る方法と、rollbackする方法でした。今回試したのは前者のremove_columnです。

**Comment by ms2sato** [comment]
@shuma1020 コメントしました。 rollbackする方法は利用できるシーンもありますが、理解してから使いましょう。まずは remove_column をちゃんと使えると良いです。

**Comment by ms2sato** [comment]
Issueは終えているのでClose
