### ISSUE TITLE
トップページで、 Productを絞り込めるようにする。

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#15]
トップページに以下のリンクを付けてください。最終的にはこれではダメですが、学習のため。

- リンク名: 全て - 内容: 全てのProduct。デフォルトはこれ。
- リンク名: 公開 - 内容: 公開の属性のものだけ
- リンク名: 下書き - 内容: 下書きの属性のものだけ 

方法は複数あります。まず一つやれる方法でやってみてください。ここは今後他の実装も試してもらうと思います。

**Comment by shuma1020** [comment]
完了しました！
コミット名です。
git commit -m "specializing release"

**Comment by ms2sato** [comment]
@shuma1020 https://github.com/shuma1020/training_app/commit/761fdc880e132039506732389caa11859267be5c

2点ほどコメントしているのでやってみてください。今のコードだと動いてはいるし間違いではないが、「らしくない」感じのコードなんです。

**Comment by ms2sato** [comment]
@shuma1020 一旦このIssueはCloseしましょう。enum を利用したこのコードはよく利用されます（releaseという名前は気になりますが、今後リファクタリングして直していきたいです。まずはちゃんと動くのが大事ですが徐々にしてきしていきます）。

サービスの内容によってこれ以外にもいくつかパターンがありますが、今後やっていきます。
