### ISSUE TITLE
[木曜][調査]sessionとは何か

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#16]
よく出てくる言葉ですが、これがなんなのか調べて続きにコメント入れといてください。
- @shuma1020 の理解
- 参考にしたWEBページなど
が欲しいです。

何も見ずに説明できてしまうのであれば文章が長くても問題ないです。むしろそれができるなら読みたいです。

**Comment by shuma1020** [comment]
読む前の理解
ログインを維持するためのもの。

ステートレスのhttp通信においてsessionはログイン情報を維持するもの。前のリクエストを忘れずに次のリクエストにも反映させる。

[https://www.sejuku.net/blog/33677](url)
[https://qiita.com/ozackiee/items/4ee774c81b2a0c571c05](url)

**Comment by ms2sato** [comment]
@shuma1020 なるほど。ちなみに Cookie って知ってますかね？ session とCookie って何か関係します？関係するとしたらどういう関係か把握できてますか？

**Comment by shuma1020** [comment]
@ms2sato cookieはユーザー側に保存させるものという認識です。ログイン情報を保存しますか？など聞かれるのはcookieが関係しているのではないでしょうか？ただsessionとの違いがいまいちわかりません。sessionはブラウザを閉じたら情報が消えてしまうがcookieは永続的に保存してくれるとかそのレベルでしか理解できていません。

**Comment by ms2sato** [comment]
@shuma1020 

> sessionはブラウザを閉じたら情報が消えてしまうがcookieは永続的に保存してくれる

お、これどこ情報？

**Comment by shuma1020** [comment]
@ms2sato railsガイド少し難しかったので下記の記事を参考にしました！
[https://qiita.com/SpicyCoffee/items/de9de9a5427adf81817a](url)
[https://railsguides.jp/security.html](url)

**Comment by ms2sato** [comment]
@shuma1020 なるほど。

https://qiita.com/SpicyCoffee/items/de9de9a5427adf81817a
の

> Railsでは基本的にsessionメソッドを使ってこの機能を実現する。sessionメソッドで作成されたセッションは自動で暗号化されるが、ブラウザを閉じると破棄される。

のことかと思いますが、この方の理解は誤っていますね。
何本か似たようなドキュメントを発見しました。なんとなく勘違いが広がっている感じです。

これ、次回対面でやりましょ。なんとなく世間を見ていると適切なドキュメンテーションが必要そうな気がしてきました。

**Comment by shuma1020** [comment]
@ms2sato 　了解致しました！
