### ISSUE TITLE
ログイン直後の日本語メッセージと、メッセージがダブってしまう問題

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#19]
![image](https://user-images.githubusercontent.com/627817/70042081-a3f8ee80-1601-11ea-9e6b-d99eac5a5825.png)

二ついっぺんにやらなくても良いですが、一旦報告しときます。

**Comment by shuma1020** [comment]
@ms2sato 
ダブりに関しては解消できそうなのですが、ja.ymlがなかなか反映させることができません。
5212aa3

**Comment by ms2sato** [comment]
@shuma1020 コメント済みー

**Comment by ms2sato** [comment]
できてはいる。ただ、 ja.yml に全部まとめ過ぎたね。本当はdevise.ja.yml を追加するだけで大丈夫だったんよ。今は不問としますー。
