### ISSUE TITLE
seed を作成する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#20]
Railsにはseedという機能があります。これを使うと簡単に初期情報のデータを作成できるものです。seedについて調べて、開発用のseedファイルを書いてみましょう。

**Comment by shuma1020** [comment]
@ms2sato  seedファイルに新たなユーザーを作成しました！

```rb
User.create!(email:"ssss@gmail.com", password:"ssssss", name:"shuma")
```
```rb
$ bundle exec rails db:seed
ShumanoMacBook-Pro:sample_app shuma$ bundle exec rails c
Running via Spring preloader in process 99282
Loading development environment (Rails 6.0.1)
irb(main):001:0> User.all
   (0.6ms)  SELECT sqlite_version(*)
  User Load (0.2ms)  SELECT "users".* FROM "users" LIMIT ?  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<User id: 1, email: "shumaseki40@gmail.com", created_at: "2019-12-01 05:51:00", updated_at: "2019-12-01 05:51:00", name: nil>, #<User id: 2, email: "1020@gmail.com", created_at: "2019-12-01 06:10:13", updated_at: "2019-12-01 06:10:13", name: nil>, #<User id: 3, email: "ssss@gmail.com", created_at: "2019-12-03 12:06:49", updated_at: "2019-12-03 12:06:49", name: "shuma">]>
```

**Comment by ms2sato** [comment]
@shuma1020 以下くらいがあると良いかと。ユーザーだけがあるのではなくて、アプリを触った時にどんな雰囲気のものかわかる様になると良いです。

プロジェクトによってこのseedの用意の仕方や重みが変わります。今回はこれを作成するコードを書くのも練習になるので丁寧にやりましょう

- User3人くらい以下みたいなわかりやすいルールが良いと思います。
  - email: user1@example.com  password: password
  - email: user2@example.com  password: password
  - email: user3@example.com  password: password
- 公開されたProduct 3つくらい
 - 3つのうち一つはrewardsなし
 - 3つのうち一つはrewards1つ
 - 3つのうち一つはrewards3つ
- 下書きProduct 2つくらい
 - 2つのうち一つはrewardsなし
 - 2つのうち一つはrewards3つ

**Comment by ms2sato** [comment]
@shuma1020 書いてくれた内容としては大丈夫です！その要領で上記の形を実現してみてください。

**Comment by shuma1020** [comment]
@ms2sato 
ba072d6
