### ISSUE TITLE
bootstrapのUIを整える

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#21]
現在以下の様なかなりレイアウトが左に寄りすぎたものになっていると思います。これはbootstrapを適切に利用できていないためです。

![image](https://user-images.githubusercontent.com/627817/70043189-5f6e5280-1603-11ea-9c73-313e865f2a78.png)

Bootstrapが何か理解して、例えば下記の様なExampleのようなある程度整った見た目にしましょう。
https://getbootstrap.com/docs/4.0/examples/

**Comment by shuma1020** [comment]
@ms2sato 
bootstrapは見た目を整えるためのものであると認識しています。class名を指定することでbootstrap上のレイアウトにすることができるものであると考えています。
d40573f

**Comment by ms2sato** [comment]
@shuma1020 理解としては良いですね。言葉として足らないのは基本的には 「CSS をうまく弄るための道具である」ということです。だからCSSの理解度がbootstrapを上手に扱えるかに影響します。

**Comment by ms2sato** [comment]
コードには色々コメントしました。

**Comment by shuma1020** [comment]
@ms2sato今fix boostrap ulを確認したのですが特にコメントが見当たらなかったのですが、 UIの関してのコメントはどのコミットにされましたか？

**Comment by ms2sato** [comment]
@shuma1020 私のコメントは以前 

https://github.com/shuma1020/training_app/issues/21#issuecomment-561111963
で貼ってくれた以下のコミットに対して行いました。
https://github.com/shuma1020/training_app/commit/d40573fa61e2cc6baa1b9150c2aa5793752aeeab

会話自体は一通り終わっている様子に認識してます。最後if文の範囲を調整して終わりましたよね。

**Comment by ms2sato** [comment]
というわけでこのIssue自体はCloseしましょう。細々またあとで指定はあるかもですが。

ちなみに、このIssueでは単純な指定をちょっと入れたら雰囲気良くなったと思うのですが、その理由って説明できたりします？

**Comment by ms2sato** [comment]
@shuma1020 
ところで、このIssueでは単純な指定をちょっと入れたら雰囲気良くなったと思うのですが、その理由って説明できたりします？

**Comment by shuma1020** [comment]
@ms2sato 
Issueのどこらへんの雰囲気がよくなったのかいまいちピンときていないのですが、どのことをおっしゃっていますか!?

**Comment by ms2sato** [comment]
@shuma1020 表現を変えます。
最初にIssueの主題であった「レイアウトが左に寄りすぎている事」は、多くの記述をしなくても解消できたと思いますが、その理由は説明できますか？

**Comment by shuma1020** [comment]
@ms2sato 
左寄せを解消できた理由に関して言うと、bootstrapの<div class="container">と連携しているからであると思います。

**Comment by ms2sato** [comment]
@shuma1020 それをもっとブレークダウンしてメカニズムが説明できればbootstrapがある程度わかって良いと言えます。上記の説明だけだと「よくわからないけどなんか動いている」ですね。もっと表現できそうなら今夜教えてください。

CSSという言葉も絡めて説明できるとかなり求められているゴールに近くなります（今できなくてもそれができるようになっていかなきゃいけないということだと理解してくれれば）。

**Comment by shuma1020** [comment]
@ms2sato 
bootstrapにはcssがモジュール化されたフレームワークが存在しており、下記のリンクによって連携を可能にしている。これらのbootstrapはクラウドサービスと推測しているのですがどうなのでしょうか
```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
```

**Comment by ms2sato** [comment]
メモ: bootstrapがどうやって有効になっているか
