### ISSUE TITLE
トップページの Product一覧を Card UIのスタイルにする

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#26]

**Comment by ms2sato** [comment]
@shuma1020 
Cardできてそうですねー。

背景画像はまだアップロードできないですが、こんな感じを目指すイメージでやってみましょうか。

![image](https://user-images.githubusercontent.com/627817/70324677-7c10c180-1873-11ea-828f-2cebdd8b6b16.png)

Productsやタイトル のような項目名は排除して良いでしょう。状態は表示しておくようにしてみてください。

### 一覧で出す項目
- タイトル
- 目標価格
- 状態
- お返しの数（これは学習のため）

### 詳細（show）で出す項目
現在一覧側に出している全て（こちらは別のIssueで見た目整えましょう）

**Comment by shuma1020** [comment]
@ms2sato 
> Productsやタイトル のような項目名は排除して良いでしょう。状態は表示しておくようにしてみてください。
とはこのようなことでしょうか？
b720b42

**Comment by ms2sato** [comment]
Cardにはなっているので終わったことにします。デザインを整えることはして欲しいので別途Issueにします。
