### ISSUE TITLE
シンボルとは何か。その利点は何か

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#27]
ちょっと浅そうなので、調べて良いと思います。調べた結果をこのIssueに書いてみましょう。

**Comment by shuma1020** [comment]
@ms2sato 
Rubyにおける配列にはarrayクラスオブジェクトとhashクラスオブジェクトがある。ハッシュの特徴はキーを持てること(キー・バリュー型のオブジェクト)
```rb
array = ["A", "B", "C"]
hash1 = {:first => "A", :second => "B", :third => "C"}  
```
ハッシュには書き方がいくつかあり、下記はシンボルを使ったハッシュである。ハッシュはシンボルを使った方が実行速度が早い。hash6は短縮形です。
```rb
hash2 = {"first" => "A", "second" => "B", "third" => "C"}
hash6 = {first: "A", second: "B"}
```
https://blog.isao.co.jp/organize-array-and-hash-and-symbol-of-ruby/　https://railsguides.jp/association_basics.html#has-many%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91
https://qiita.com/ryosuketter/items/257d672eb83210b5f8dc

**Comment by ms2sato** [comment]
@shuma1020 ちょっと色々と話を書き過ぎている感があるので

シンボルについてだけまとめましょうか。
もともと @shuma1020 さんの「シンボルの利点が可読性だけか？」ということへのアンサーを自分で調べるためのIssueですよ。

**Comment by shuma1020** [comment]
@ms2sato シンボルの利点は
-　可読性
- メモリ消費
- 処理速度が文字列に比べて早くなる

文字列にコロン記号「:」をつけると、シンボルになる。
メソッドなどの名前を識別するためのラベルをオブジェクト化したもの。

**Comment by ms2sato** [comment]
@shuma1020 ほぼ良いかと！読みやすいだけではなくて性能が良いものになります。
