### ISSUE TITLE
productの詳細画面を整える

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#29]
https://camp-fire.jp/projects/view/209254?list=key_visual
こんな感じのレイアウトを目指していきたいです。

左右にレイアウトしていくには grid という仕組みがBootstrapにあるので使ってみてください。
また、スマホのWEBのような縦長になった場合のレイアウトもgridを工夫するとできるので対応してみましょう。

※ 今は一旦Gridの練習ということでカッコいいデザインまではやれなくて大丈夫です。

**Comment by shuma1020** [comment]
@ms2sato 
af81a22
こちらのサイトを参考にしました！
http://websae.net/twitter-bootstrap-grid-system-21060224/

**Comment by ms2sato** [comment]
@shuma1020 対象がちがうよー。 詳細画面と言うと、一般的には `show` アクションの画面だよー。

**Comment by shuma1020** [comment]
@ms2sato d703869

**Comment by ms2sato** [comment]
@shuma1020 gridという機能を利用して、と指定がありましたが、あまり掴めていない様子（それっぽいのは書きたいことは伝わる。本質が掴めてない可能性高い）。何か読んだりしてますか？

**Comment by shuma1020** [comment]
@ms2sato これらを参考にしました。
http://websae.net/twitter-bootstrap-grid-system-21060224/
https://getbootstrap.jp/docs/4.2/layout/grid/
https://qiita.com/akatsuki174/items/53b7367b04ed0b066bbf

**Comment by ms2sato** [comment]
もう少し色々やっても良いが、一旦終わったことにします。
