### ISSUE TITLE
rails c を利用してデータを操作する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#3]
rails  c を使って 新しくproductを作り、 rewardを2個追加してください。

操作したコマンドの履歴をこのIssueのコメントに貼ってください。

**Comment by shuma1020** [comment]
`irb(main):007:0> Product.create(title:"新たに追加", description:"追加")
   (0.1ms)  begin transaction
  Product Create (0.6ms)  INSERT INTO "products" ("title", "description", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["title", "新たに追加"], ["description", "追加"], ["created_at", "2019-11-30 13:28:41.336287"], ["updated_at", "2019-11-30 13:28:41.336287"]]
   (1.7ms)  commit transaction
=> #<Product id: 6, title: "新たに追加", price: nil, description: "追加", created_at: "2019-11-30 13:28:41", updated_at: "2019-11-30 13:28:41", message: nil, status: 0>
irb(main):008:0> Reward.create(title:"追加リワード", product_id:6)
   (0.1ms)  begin transaction
  Product Load (0.3ms)  SELECT "products".* FROM "products" WHERE "products"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  Reward Create (0.7ms)  INSERT INTO "rewards" ("title", "product_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["title", "追加リワード"], ["product_id", 6], ["created_at", "2019-11-30 13:29:38.656260"], ["updated_at", "2019-11-30 13:29:38.656260"]]
   (1.7ms)  commit transaction
=> #<Reward id: 8, title: "追加リワード", description: nil, price: nil, product_id: 6, created_at: "2019-11-30 13:29:38", updated_at: "2019-11-30 13:29:38">`

**Comment by ms2sato** [comment]
Good!
