### ISSUE TITLE
[管理画面] routingのnamespaceについて調べる

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#30]
今のURL構造は、全ての人が同じURLを見ることができるような仕組みです。
多くのシステムは「ログインしている人だけが入れるページ」や「管理者、編集の場合のページ」など特定の人だけが入れるページを作ります。

この方法の一つとして、URLに対象の人専用の階層を作ります。例としては例えば以下のようなことです。

- `/admin`の下: 管理者専用の操作をこの下にする
- `/admin` には、 Userのうち「管理者」という属性が割り当てられた人しか入れない

実際のサービスでは管理者画面に沢山の機能が実現されますが、今回はまず一歩目として「管理者画面のトップ（ '/admin' ）に全てのProductのリストが新着順でテーブル表示される」
という形を目指しましょう。

今まで既に自力で実装してくれているコードから推察すると、 routingのnamespaceについての調査をすると、必要な情報が揃いそうです。まずは調べて手を動かしてみる、という形にしましょう。

また、変更を戻したくなる可能性があるので、この機能はブランチを作成してやってみてください。
- ブランチ名: `admin`

ブランチを使い始めると「今どのブランチにコミットすべきか」を考えないといけなくなります。`admin`ブランチをcheckoutしている時には、adminの作業だけコミットするようにします（管理画面以外の修正は masterブランチに commit するようにします）

**Comment by shuma1020** [comment]
@ms2sato ここでいう管理者とはログインしているユーザーのことではなく、開発者のこと(今回は自分)ですか？

**Comment by ms2sato** [comment]
@shuma1020 上記の理解で概ね大丈夫です。このサービスだと以下のような権限（ロールと言います）がありそうだとイメージしています。

- ユーザー（Productの作成ができる。作成しないで単純にパトロンになるだけでも良い）
- 管理者（サービス管理権限を持っている人）

そして実際に実現する上では、 Userにroleのようなenumを付けられる形で良いでしょう（この手法は実際によく使われます）。

**Comment by ms2sato** [comment]
Finished!
