### ISSUE TITLE
[デグレード？] シンボルだったはずのところが文字列に戻っているので対応しましょう

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#31]
デグレードという言葉は馴染みがないと思うので調べてみてください。「デグレ」と呼称したりします。

seed.rb の中の status の指定が シンボルから文字列になってしまっているので修正しといてください。また、priceのインデントもスペース抜けが見えるので入れておきましょう。

ちょっと神経質な指摘でもありますが、せっかくやったのと、デグレという言葉についての理解のためIssueかしてみました。

**Comment by shuma1020** [comment]
@ms2sato  :がシンボルであると認識していたのですが、下記は文字列になるのですか？
```
status: "draft"
```

**Comment by ms2sato** [comment]
@shuma1020 `status: :draft` とします。keyではなく、valueの話です。

**Comment by ms2sato** [comment]
理解できた様子。close
