### ISSUE TITLE
[管理画面] /admin の階層を作成する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#32]
ref https://github.com/shuma1020/training_app/issues/30

- Userにroleを作成し、一般のユーザーと管理者を区別できるようにする
- /admin の namespaceを作成する
- 今回は、 /admin のURLで Product一覧のテーブルを表示するようにする（新着順）
- roleが管理者の人しか /adminの下にはアクセスできない

**Comment by shuma1020** [comment]
@ms2sato 
上から三つはできて最後の一つをやろうとしているのですが、そもそもroleがユーザーか管理者かは誰が決めるのでしょうか？statusと同じような感じでroleを追加したのですがこれでは誰でも管理者になることができてしまいます。
17808e5

**Comment by ms2sato** [comment]
@shuma1020 決めるのは管理者である @shuma1020 が任命できる形で良いですね。

丁寧にやるならそれをやれる専用のUIを作ったりしますが、 rails c などで調整できれば良いので（管理者がたくさん必要なことは無いですよね）、WEBからの変更は入れなくて良いですよ。デフォルトを一般ユーザーにしておければ大丈夫です。

**Comment by ms2sato** [comment]
@shuma1020 ブランチでのコード変更が見やすいので https://github.com/shuma1020/training_app/pull/33 を作成しました。コードについてのやりとりはここを中心にすると良いでしょう。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！
