### ISSUE TITLE
ProductのformでUserIDを入力しなくて良いようにしたい

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#35]
ユーザーでログインできるようになったので、これがやりたいですね。
もしもすぐコードが書けそうなら書いてしまって良いですよ。

不安であればどういう実装にするかここに書いてみてください。

**Comment by ms2sato** [comment]
@shuma1020  このコードでやろうとしていることを提示してください。

```rb
    def setting
      current_user.id == @products.user_id
    end
```

また、before_actionに頼りすぎではないでしょうか。createアクションやupdateアクションが関係するアクションになると思うので、そのアクションに関係するところにだけコードを書けば良いと思います。 before_action はあくまで複数のアクションに一度に共通の処理を加えたい時に使えば良い便利な道具程度の認識で良いです。

**Comment by shuma1020** [comment]
@ms2sato 
訂正済みです！
