### ISSUE TITLE
「パトロンになる」を設計する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#36]
# 大まかな仕様

- 他人が作成したProductに **のみ**「パトロンになる」というリンクを表示
- 上記のリンクを押すと押したユーザーがProductのパトロンになれます
- パトロンになった人は products/:id の画面に名前が出ます

# 設計

- [x] DB設計（どんな構造なら実現できるでしょうか）
- [x] Controller/Action の変更（追加するなら何を追加するか）
- [x] 他にも何かいじるなら

上記の内容を決めたら このIssue上で @ms2sato に報告すること

**Comment by shuma1020** [comment]
- パトロンになるのはユーザーなのでuser.idをうまく利用するのではないか
- patron_idをProductテーブルに作る
-パトロンになるにはcurrent_user.id !=product.user_idである必要がある
1. patron_idを追加する
2.ProductsController#Createにif current_user.id !=product.user_idを加える
3.formを作る

ただ今回はパトロンになるかならないかの二択。セレクトでもできないことはなさそうですが、パトンになるというボタンを押したらすぐに反映されるのが理想です。

**Comment by ms2sato** [comment]
@shuma1020 この時に考えないといけない点として

- Userは幾つのProductのパトロンになれるだろうか
- Productは何人のUserからパトロン登録されるだろうか

です。今提示してくれた仕様だと Productは一人のユーザーからだけパトロンとして登録される形になると思います。これだと同じProductにたくさんの人が登録できません。さて、どうしたら良いでしょう。もしも困ったら「多対多」という構造を調べてみてください。

このIssueで一旦パトロンとして登録することが実現できたら、それを拡張して「いくら支払うか指定してパトロンになる」というのをやります（一旦「そういう予定かー」くらいで大丈夫です）。

**Comment by ms2sato** [comment]
@shuma1020 これは手が空いたら進めて大丈夫です。上記でポイント出してみているので考えてみましょう。

**Comment by shuma1020** [comment]
@ms2sato 　patronというブランチを作ったのでそちらにpushします！

**Comment by ms2sato** [comment]
@shuma1020 一応伝えておきますが「DBがどのように変更されるか」が決められていなかったので「DB設計が終わっていない」という認識を私はしています。なので手を動かすのは早すぎたです。

https://github.com/shuma1020/training_app/issues/36#issuecomment-563144948
私から質問も投げかけているので、まずこれに答えるべきでした。そうじゃないと単純に手戻りが発生して時間が無駄になると思うからあえて確認を求めています。

再開する時にまずここからやることを進めます。

**Comment by shuma1020** [comment]
@ms2sato 
>Userは幾つのProductのパトロンになれるだろうか
Productは何人のUserからパトロン登録されるだろうか
複数のProductのパトロンになれる
複数人からパトロン登録される

- 中間テーブルagentsを用意　
- agentsテーブルは二つのテーブルに従属している。(belongs_to :product belongs_to :user)(product とuserの外部キーを保持している user_id product_id)
- ProductとUserはAgentを通してお互い関連しあっている。つまりproductsテーブルはhas_many :users、usersテーブルはhas_many :productsと記載する必要がある。(名前はitemsとpatronsに変更ずみ)
- お互いカラムには外部キーであるidを保持している。(user_id,product_id)

**Comment by ms2sato** [comment]
@shuma1020 ありがとう。ここで、中間テーブルを `patrons` にしなかった理由ってありますか？ `users` と `products` の関係性が `patrons` では無いかなと感じます。私だと確実に `patrons` と付けるところです。

名前以外は大きな問題を感じていないし、既に書かれたコードもザッとは見ていますが「自然な名前付け」をできる感覚が持てるとより良さそうだと感じています。

**Comment by shuma1020** [comment]
@ms2sato 最初にやるときに仲介するみたいな意味をつけたかったので、agentにしたのですが途中でpatronの方がよかったと思ったのですが途中で変えると頭がこんがらがりそうなのでそのままにしました。

**Comment by ms2sato** [comment]
@shuma1020 背景ありがとう。こういう感じの「何かと何かの関係性を中間テーブルで表す」のは良くあるので名前付け含めて慣れていけると良いです。理解しているなら変更するコストをかけるほどでもないので今回はagentで進めていきましょう。

**Comment by ms2sato** [comment]
メモ: 設計と実装という言葉を知ること
