### ISSUE TITLE
localeのファイルをモデル毎に分ける

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#37]
i18nのlocaleの内容ですが、 ja.yml に全てが入っていると思います。このファイルを分割しましょう。

- deviseの内容を devise.ja.ymlに
- 各モデルの内容を model ディレクトリを作ってその中に
  - productの内容であれば `config/locales/model/product.ja.yml`
  - model階層の追加の仕方について `config.i18n.load_path` を調べてみると良いでしょう。

**Comment by shuma1020** [comment]
@ms2sato 
いくつか記事を参考にし、試したのですがうまく連携できません。
原因として挙げられるのはディレクトリの名前というよりも、ja.ymlの中身にあるのかと考えているのですが具体的にどこが間違っているのか悩んでいます。
https://railsguides.jp/i18n.html#%E3%83%AD%E3%82%B1%E3%83%BC%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E7%B7%A8%E6%88%90
aab71c7

**Comment by ms2sato** [comment]
@shuma1020 別途ブランチ作ってPR（PullRequest）上で進めましょう。どういう変更を試みたのかが私に伝わらなければアドバイスができません。

また「うまく連携できません」 という言葉はやめましょう。エラーが起きているならどんなエラーが起きたのか書くべきですし、そうで無いとすると、想定する動作との違いを表現しないといけないシーンです。

**Comment by shuma1020** [comment]
@ms2sato 了解です。エラーは特にありません。rewardモデルの英語がconfig/locales/models/reward/ja.ymlによって日本語になることを期待しているのですが、それがうまく反映されません。

**Comment by shuma1020** [comment]
@ms2sato ymlブランチを作成いたしましたので、今後localeに関してはこちらでpushします！

**Comment by ms2sato** [comment]
@shuma1020 PullRequestも作ってくださーい。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！

**Comment by ms2sato** [comment]
残項目はあるものの、できた！
