### ISSUE TITLE
ProductにUserIDを関連づける際のより良い方法を適用する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#39]
ref https://github.com/shuma1020/training_app/issues/35

https://github.com/shuma1020/training_app/commit/5a8ad2cf265ad185e1633702fb40114eceadf489

これで動作は大丈夫だと思います。
ControllerでProductにUserIDを関連するコードについてですが、seedを書く時にやっているアソシエーションを利用する方法を使う方が推奨されているので、その書き方で行きましょう。

これをやっておくと「current_userに関連する情報をいじるのだ」ということが明瞭になります。
もちろん元の書き方も場合によっては利用しますのでどちらもできるようにしておいてください。

**Comment by shuma1020** [comment]
@ms2sato 
```rb
 def create
    @product = Product.new(product_params)
    current_user.id = @product.user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
```
@ms2sato 
上記のようにしたのですが、うまくいきませんでした。
- @productがProduct モデルより作られたインスタンス変数だと知る
- @productに対してuserが呼ばれていると認識する。productモデルにuserが定義されていればuserを呼び出すことができる
-この結果AcitveRecord::Relationが戻ってくる
-idを読んでいる

このような流れになることを期待して、上記のような記述をしました！

**Comment by ms2sato** [comment]
@shuma1020 解説読んだのだけど、すまない。私は意図が把握できなかったので、まず先に以下を確認させてください。

- current_user は何か（意味合いと、型を示して欲しいです。型という言葉が微妙ならモデル名でも良いです）
- product_params の中には何が入っているか

**Comment by shuma1020** [comment]
@ms2sato すいません!自分が説明したのは３行目のcurrent_user.id = @product.user.idの部分です。上記の記述は以前slackにて解説していただいたのを元に応用したのですが、どのあたりに不明点があるでしょうか？

- サインインしているユーザーを取得する 　rails g devise userで生成したUserモデルだと思います。
- product_params の中には何が入っているか
```def product_params
      params.require(:product).permit(:title, :price, :description, :message, :status, :user_id, :image, :image_cache, :remove_image)
    end
```

 - @productはProductモデルにて:title, :price, :description, :message, :status, :user_id, :image, :image_cache, :remove_imageを新たに作成したインスタンス変数


> @product.user_id=current_user.id 

に関して言えば現在サイインしているユーザーがproduct生成者と等しい。ただ今回のissueではこの書き方ではなくアソシエーションを用いてより良い方法を適応する、ということだと思うのですがアソシエーションを用いたやり方がわかりません。

**Comment by ms2sato** [comment]
@shuma1020 ちょっと最初の質問をあえてスルーしてしまうけれど（多分今後きっちり明らかにできると思う。言いたいことはある程度理解できたよ）。

- サインインしているユーザーを取得する
  - 大丈夫だと思います
- product_params の中身
  - `params.require(:product).permit(:title, :price, :description, :message, :status, :user_id, :image, :image_cache, :remove_image)` これがそのまま入っていますか？
  - メソッドが呼び出されると順番に評価されて、最終的に何か戻り値が返っていると思います。その姿が表現できると良いです。なのでどこのコードが呼ばれた結果かではなくて、どんな評価結果になっているかを書いて欲しいです。

3. ちょっと長くなるので列挙から外しますが、以下の2つを @shuma1020 は「同じことをしている」と理解している様子ですが、合っていますか？

```rb
current_user.id = @product.user.id
```

```rb
@product.user_id=current_user.id
```

4. 「上記のコードが 変数の代入と同様の動作になる」と表現したら何か気づく点はありますか？

**Comment by shuma1020** [comment]
- product_paramsの中身
  -  paramsメソッドとrequireメソッドによって指定のパラメーターのみ(今回はproductモデル)を受け取り、permitによって:title, :price, :description, :message, :status,  :imageのみを今回の場合は許可する
3. 上記は前者はアソシエーションを利用したもので、後者はproductモデルにあるuser_idを利用したものだと理解しています。結果として同じ表現になるのではないかと思い、改善案として後者を記述していたのですがうまくいきませんでした。
4. それは右辺のオブジェクトを左辺に代入するということでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 もうひとこえ！

- product_paramsの中身: product_paramsはメソッドだと思うのですが、私の「中身」という表現が悪かったですね。戻り値として評価されている値はもっと具体的だと思うのですがどんなものですか？型と中身の例示が欲しいです。

3. `結果として同じ表現になるのではないかと思い` 残念、これが間違いです。そして4がこれに関連しています。

4. YESです。そして `current_user.id = @product.user.id` なら current_user が所有している id という要素に `@product.user.id` の戻り値を代入します。

**Comment by shuma1020** [comment]
- 　つまりproduct_paramsメソッドの戻り値は何かということでしょうか？title stringなどかと推測したのですが、もっと具体的な値があるということですよね？

3.　ちなみにこの理解はあっていますか？
> 上記は前者はアソシエーションを利用したもので、後者はproductモデルにあるuser_idを利用したものだと理解しています。

4. そうすると左辺と右辺を下記のように入れ替えると意味合いは異なり、@product.user.idという変数にcurrent_user.idを代入するとなるという認識でよろしいでしょうか？
```rb
@product.user.id=current_user.id
```

下記のコードはproductモデルがuserを確認しリレーションが返ってきてidを呼びそれをcurrent_user.idにした。
```rb
current_user.id = @product.user.id
```
こちらはcurrent_user.idがオブジェクトとして@product.user_idに代入された。つまり現在サイインしているユーザーはproduct生成者になるということ
```rb
@product.user_id=current_user.id
```

**Comment by ms2sato** [comment]
@shuma1020 
-  `product_paramsメソッドの戻り値は何か` YES! 型の名前と、その中身を例として示してください。

3. ここで望まれている事としてはNOです。
https://github.com/shuma1020/training_app/issues/40
こっちの知識を持ちて書けませんか？ という話ですよ。向こうができていてこっちではできないというのは何か先入観があるから？

4. 

> そうすると左辺と右辺を下記のように入れ替えると意味合いは異なり
YESデス。

> @product.user.idという変数にcurrent_user.idを代入する

ちょっとニュアンスが違うので細かく指摘しますが、 @product 変数のuser要素（userプロパティと読んだりします）の id要素に、 current_user.id を代入するという感じでしょうか。
ここでは変数はあくまで @product で、あとはメソッドしかないです。

そして、基本的に右辺の値は全部評価された最後の戻り値が代入される値になります。

> current_user.idがオブジェクトとして@product.user_idに代入された

は丁寧に書けば以下のような感じ。

current_user.id は数値で、その数値が @product.user_id に代入されます。もちろんこのままsaveなどで保存成功すれば @productは current_user と関連づいて保存されます。

**Comment by shuma1020** [comment]
- :title, :price, :description, :message, :status, :imageが中身で、それぞれstring,integer,string,string,integer,stringだと思うのですがどうやらこれではないみたいですね。product_params = { title:'テスト', description: '説明' }でいうと右辺の部分
3. #40　が関連していることは重々承知しているのですが、何か勘違いしてしまっているかもしれません。改めて整理してみます。
前者は#40のこの部分に当たるのではないでしょうか?つまりcurrent_user.idを何か定義している
 ```rb
current_user = User.last
```
```rb
current_user.id = @product.user.id (前者)
```

4. 
下記は左辺と右辺の意味合いは異なるという例で提示したもので、今回のissueはその行の下に当てはまるのかと考えています。
>@product.user.idという変数にcurrent_user.idを代入するとなるという認識でよろしいでしょうか？

>下記のコードはproductモデルがuserを確認しリレーションが返ってきてidを呼びそれをcurrent_user.idにした。
```
current_user.id = @product.user.id
```

**Comment by ms2sato** [comment]
@shuma1020 

> 型の名前と、その中身を例として示してください

戻り値の「型の名前」に言及がないです。戻り値の型に含まれている値が保有している複数の型については書いてくれていますが、それは重要では無いです。

`{ title:'テスト', description: '説明' }` これの型は何ですか？


##  3. アソシエーション

端的に回答だけしておくと、この二つがやっていることは全く違うものです。

```
current_user = User.last
current_user.id = @product.user.id (前者)
```

一番最初に書いてあるメッセージを改めて掲載します。

> ControllerでProductにUserIDを関連するコードについてですが、seedを書く時にやっているアソシエーションを利用する方法を使う方が推奨されているので、その書き方で行きましょう。

seedを作成する時に `Product.create!(user_id: user.id, ...）` のように書いていた場所を `user.products.create!(...)` のようにすることで、 user_id の指定がオブジェクトを介して行える形に直したと思います。 ここでやったのは `user.products` のようなアソシエーションで出来上がるメソッドを利用して `user.products.create!` の形で「オブジェクトの親子関係をわかりやすくしながら作成」できたということです。

https://github.com/shuma1020/training_app/issues/24

アソシエーションを利用していれば何でも良いということではなくて、seedの作成のところで理解できたと思われる内容を使って書きましょう、という事です。

この話、対面でやりましょう。

**Comment by shuma1020** [comment]
@ms2sato データ型でしょうか？
了解です！

**Comment by ms2sato** [comment]
LGTM!
