### ISSUE TITLE
[Rails cでやる] ユーザーに関連した新しいProductを作成する方法

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#40]
下記のように、 product_paramsと、current_userが変数として入っている前提で、このユーザーに新しいProductを関連づけて保存してください。

```
irb(main):002:0> product_params = { title:'テスト', description: '説明' }
=> {:title=>"テスト", :description=>"説明"}
irb(main):003:0> current_user = User.last
  User Load (0.3ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT ?  [["LIMIT", 1]]
=> #<User id: 3, email: "user３@example.com", created_at: "2019-12-07 02:08:43", updated_at: "2019-12-09 05:52:49", name: "user3", role: nil, admin: true>
```

**Comment by shuma1020** [comment]
@ms2sato こちらでよろしいでしょうか！このようなrails cでアソシエーションの理解を確かめるのは非常に為になるのでもっと定着するようにやりたいです！
```
product = current_user.products.new(product_params)
=> #<Product id: nil, title: "テスト", price: nil, description: "説明", created_at: nil, updated_at: nil, message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
irb(main):005:0> 
```

**Comment by ms2sato** [comment]
@shuma1020 これ、私がIssue出しているのはきっかけを与えただけだよ。

こういうのを自分で色々試して自習して欲しいです。実際にはそうやって自分で色々書いてみて学ぶ必要があるんです。

で、これをあえてアサインしなかった理由は https://github.com/shuma1020/training_app/issues/39 と関係するからなんですよ。

**Comment by ms2sato** [comment]
@shuma1020 

例えば以下のようなのをやるのどうですか？自分でも考えてやってみること。

- `product = current_user.products.new(product_params)` で作ったproduct をDBに保存までする。
- 「一度 new 的なもので作成し、変更してから保存」というコード（Scaffoldのcreateアクションなどでよく見るやつ）
- 「いきなり create」 するコード
- 「内容が足らないなどでバリデーションエラー」になるコード

**Comment by shuma1020** [comment]
@ms2sato 
- saveは一度priceを入力していないと弾かれましたができました
```rb
 product.save!
   (0.3ms)  begin transaction
  Product Create (0.7ms)  INSERT INTO "products" ("title", "price", "description", "created_at", "updated_at", "user_id") VALUES (?, ?, ?, ?, ?, ?)  [["title", "テスト"], ["price", 200], ["description", "説明"], ["created_at", "2019-12-10 12:51:30.062985"], ["updated_at", "2019-12-10 12:51:30.062985"], ["user_id", 3]]
   (1.3ms)  commit transaction
=> true
```
- scaffoldのcreateにあるのはProduct.newとrespond_toだと思いますが、このお題にどう関係しているのかいまいちわかりませんでした。
```rb
product
=> #<Product id: 7, title: "テスト", price: 200, description: "説明", created_at: "2019-12-10 12:51:30", updated_at: "2019-12-10 12:51:30", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
irb(main):017:0> product.title ="部活の大会"
=> "部活の大会"
irb(main):018:0> product
=> #<Product id: 7, title: "部活の大会", price: 200, description: "説明", created_at: "2019-12-10 12:51:30", updated_at: "2019-12-10 12:51:30", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
```
- いきなりcreate兼バリデーション (バリデーションがエラーが表紙されるのは！をつけるかつけないか)
```rb
product2 = current_user.products.create!(product_params)
   (0.2ms)  begin transaction
  Product Create (0.6ms)  INSERT INTO "products" ("title", "price", "description", "created_at", "updated_at", "user_id") VALUES (?, ?, ?, ?, ?, ?)  [["title", "テスト"], ["price", 200], ["description", "説明"], ["created_at", "2019-12-10 13:02:34.241098"], ["updated_at", "2019-12-10 13:02:34.241098"], ["user_id", 3]]
   (1.4ms)  commit transaction
=> #<Product id: 8, title: "テスト", price: 200, description: "説明", created_at: "2019-12-10 13:02:34", updated_at: "2019-12-10 13:02:34", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
irb(main):023:0> 
```

**Comment by ms2sato** [comment]
@shuma1020 

> scaffoldのcreateにあるのはProduct.newとrespond_toだと思いますが、このお題にどう関係しているのかいまいちわかりませんでした。

createアクションは

newして、変更して、 保存（保存がまだしてない）

という流れになることが結構あります。
https://github.com/shuma1020/training_app/commit/5a8ad2cf265ad185e1633702fb40114eceadf489
もそうですよ。

で、保存までお願いします！

`rails c` はとても扱いやすい道具なので、困った時にはここでコードの動作を確認する癖を付けましょう。

**Comment by shuma1020** [comment]
@ms2sato 
なるほど！つまり下記のはcreateを意味していたということですか？
> 「一度 new 的なもので作成し、さらに変更してから保存」
createすると保存も一連の流れで行ってくれるのではないでしょうか？保存はまだしていないというのはどこの箇所のことでしょうか！？5a8ad2c　のことですかー？
```
<Product id: 8, title: "テスト", price: 200, description: "説明", created_at: "2019-12-10 13:02:34", updated_at: "2019-12-10 13:02:34", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
```

**Comment by ms2sato** [comment]
@shuma1020 

https://github.com/shuma1020/training_app/issues/40#issuecomment-564023095

で提示されている下記のコードは保存していないですよ。取ってきた情報を操作はしたけれど、DBに反映されません（DBに反映されていないなら保存はされていません）。

```rb
product
=> #<Product id: 7, title: "テスト", price: 200, description: "説明", created_at: "2019-12-10 12:51:30", updated_at: "2019-12-10 12:51:30", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
irb(main):017:0> product.title ="部活の大会"
=> "部活の大会"
irb(main):018:0> product
=> #<Product id: 7, title: "部活の大会", price: 200, description: "説明", created_at: "2019-12-10 12:51:30", updated_at: "2019-12-10 12:51:30", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
```

> なるほど！つまり下記のはcreateを意味していたということですか？

厳密にはNOです。createしたのと同じ結果（保存されるDBの情報が同じというのが「同じ結果」ということ）にできる方法が複数通りあります。

> 「一度 new 的なもので作成し、さらに変更してから保存」

https://github.com/shuma1020/training_app/commit/5a8ad2cf265ad185e1633702fb40114eceadf489

この提示したコードも、モデルのcreateメソッドは使っていません。
コントローラーのアクション名が createであることと、モデルのどのメソッドを使うかは特に関係がないです。

---

下記のコードで、どの段階でDBに保存されるかわかりますか？

```rb
   @product = Product.new(product_params)
   @product.user_id=current_user.id
   respond_to do |format|
      if @product.save
```

**Comment by shuma1020** [comment]
@ms2sato あっ、product_id :7のことですね。８のことをおっしゃているのかと思っていたのですが、8は保存できたとみてよろしいですか？

なるほど、if @product.saveでないでしょうか？
> 下記のコードで、どの段階でDBに保存されるかわかりますか？

**Comment by shuma1020** [comment]
@ms2sato 
今改めてターミナルを確認したのですが、product.saveはしてありこのメッセージに添付していなかっただけみたいです。
```
product.title ="部活の大会"
=> "部活の大会"
irb(main):018:0> product
=> #<Product id: 7, title: "部活の大会", price: 200, description: "説明", created_at: "2019-12-10 12:51:30", updated_at: "2019-12-10 12:51:30", message: nil, status: "draft", user_id: 3, image: nil, patron_id: nil>
irb(main):019:0> product.save
```

**Comment by ms2sato** [comment]
@shuma1020 id:8 については INSERTがSQLで発行されてcommit transaction されているから保存成功していますね。

id:7 についてOKです。product.save の後に 8と同様にUPDATEのSQLが発行されていれば大丈夫だと思います。

一旦この件概ね大丈夫そうなかな。どっちかって言うと私たちはテキストコミュニケーションで苦労している様子に見えるので、明日少し調整していきましょう。 @shuma1020 ができているのをできていないように錯覚してしまうのは勿体無いし、逆に理解できてないことをできていると勘違いしてしまうのも困るので。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！ではこの件は対面でよろしくおねがします！

**Comment by ms2sato** [comment]
```
@product = current_user.products.new(product_params)
```

**Comment by shuma1020** [comment]
@ms2sato 今 コンソールをいじっていていて下記の二つのコードを試してみました。
前者は通るかな、と思ってやったのですが通りませんでした。なんで通らなかったのか考え、**Productモデルのどのレコードか指定できてないからではないか**と推測し、後者のコードを試したらうまくいったのですが、この推測はあっていると言えるでしょうか？？
```rb
Product.rewards.create!(title: "aaa", price: 100, description: "3333")
```
```rb
Product.find(1).rewards.create!(title: "aaa", price: 100, description: "3333")
```

**Comment by ms2sato** [comment]
@shuma1020 Productを含んでいる`ActiveRecord::Relation` のオブジェクトには rewards メソッドが定義されていません。 createやnewは`ActiveRecord::Relation`にもともと定義されているものなので使えます。

Productに`has_many :rewards` したら、あくまで Product モデルにメソッドが追加されます。
Productのインスタンスが rewardsを呼べる。単体でしか使えないということになります。

**Comment by ms2sato** [comment]
@shuma1020 タスクが存在するわけでは無いのでCloseしますね。この手のやつで質問発生したらSlackでも良いですー。

**Comment by shuma1020** [comment]
@ms2sato なるほど下記の部分がいまいち理解できていません！
> createやnewはActiveRecord::Relationにもともと定義されているものなので使えます。

**Comment by ms2sato** [comment]
@shuma1020 `pps.rewads` で戻ってくるのは ActiveRecord::Relation の型で、その型には create メソッドや new メソッドがあります。だから使えます、という意味です。
