### ISSUE TITLE
「current_user.role == "staff"」 を enumの機能で書く

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#42]
https://github.com/shuma1020/training_app/pull/33#discussion_r356027224

**Comment by ms2sato** [comment]
そろそろできそうなので、やりますか。grepして対象のところを編集お願いします。

**Comment by ms2sato** [comment]
@shuma1020 これの対応どこでやりました？該当のコード部分をURLで下さい。

**Comment by shuma1020** [comment]
@ms2sato トランザクションのブランチでやっていました。admin/products_controllerのadmin_checkアクションです
