### ISSUE TITLE
bootstrapのalertのデザインを適用する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#43]
![image](https://user-images.githubusercontent.com/627817/70583687-d73f0d00-1c01-11ea-8a06-1fce164497a1.png)

noticeやalertの部分にデザイン入れましょう

**Comment by ms2sato** [comment]
管理画面については確認。ちょっと他も含めて一度整理しないと、表示されるはずが抜けたりしている。

**Comment by shuma1020** [comment]
@ms2sato 了解です！確か一度田ぶったところなどを削除したりした記憶があるので、その際に間違えて消してしまった可能性高めです！

**Comment by shuma1020** [comment]
@ms2sato 通常時は何も表示しないように設定し直しました！

**Comment by shuma1020** [comment]
@ms2sato alertバージョンも作成しました！

**Comment by ms2sato** [comment]
notice と内容揃ってない（意味は同じ）だけど、一旦OKとしまーす。
