### ISSUE TITLE
HTMLの基本構造

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#44]
よくあるhtmlの構造について。

1. 基本知識の確認
`<html></html>`のタグの直下には大抵入るタグが決まっています。何が入るか書いてください。

```
<html>
</html>
```

2. サービスを直しましょう
1が終わったらやります。
現在作成中のサービスで上記に従っていない部分があったら直しましょう。

**Comment by shuma1020** [comment]
1.  　headは主に訪問者には見られないもので、linkタグやmetaタグを入れる。metaタグは文字コードの指定や、ブラウザでの表示のさせ方を指定する。linkタグはCSSファイルの読み込み指定をしたり、ページ同士の関係性を検索エンジンに伝えたりする。
bootstrapやfont awesomeなどを使うときはここにリンクを貼ることが必要。
```rb
<head>
        <meta charset="UTF-8">
        <title>HTML5</title>
    </head>
    <body>
        文章の内容
    </body>
```

**Comment by ms2sato** [comment]
@shuma1020 Good！ では現在のサービスでこの構造に従っていないか確認してまずそうな箇所を修正してください。

**Comment by shuma1020** [comment]
@ms2sato 確認しました！

**Comment by ms2sato** [comment]
@shuma1020 問題なかった、という報告でしょうか？ <html>の下に<head>と<body>以外が入っていると思うので、修正必要と思います。再確認ください。

**Comment by shuma1020** [comment]
@ms2sato 下記のようなものが必要ないということでしょうか？ 「の下にと以外が入っていると思うので」というのが読み取れませんでした。
```rb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <%=link_to 'クラウドファンディング', root_path, class:"navbar-brand"  %>
           <% if user_signed_in? %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to '製品', new_product_path, class:"nav-link"%>
            </li>
            <li class="nav-item active">
              <%= link_to 'お返し', new_reward_path, class:"nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to '下書きのみ', draft_products_path, class:"nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to '公開', release_products_path, class:"nav-link" %>
            </li>
          </ul>
          <% end %>
      </nav>
```

**Comment by ms2sato** [comment]
@shuma1020 必要でしょうが、今の場所ではダメです。 bootstrapのサンプルなどをみてもこういう場所には入っていないと思いますよ。

**Comment by ms2sato** [comment]
@shuma1020 あー、ごめーん。`<head>` と `<body>` でした。編集押してくれると私がしくじったことが確認できると思います。

**Comment by shuma1020** [comment]
@ms2sato 変更してみました！

**Comment by ms2sato** [comment]
@shuma1020 https://github.com/shuma1020/training_app/blob/master/app/views/layouts/admin.html.erb

こちらも対応したらcloseして大丈夫です。

**Comment by shuma1020** [comment]
@ms2sato 対応したのですが、nestbranchで対応してしまいました。ここで変にmasterも編集するとconflictすると思うので、とりあえずこのままにしておきます！

**Comment by ms2sato** [comment]
nestの方で確認できたのでIssueは一旦Closeします。
