### ISSUE TITLE
mypage をnamespaceで作成する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#46]
adminと同様にmypage階層を作成しましょう。現場で合わせた感じだとこの画像の雰囲気です。
![Image from iOS (8)](https://user-images.githubusercontent.com/627817/70790501-89303200-1dd8-11ea-9102-e8e3f1d359d7.jpg)

**Comment by ms2sato** [comment]
@shuma1020 アサインだけ変更されたように見えています。masterに変更がある様子には見えなかったので、どこをみたら良いか教えてください。

**Comment by shuma1020** [comment]
@ms2sato あっマイページに関してはnestブランチでやっているのでそちらで更新したという意味で、アサインを変えました！

**Comment by ms2sato** [comment]
@shuma1020 #47 のように Issueや PRの番号を入れるとリンクになるのでそれを示すと良いですね。情報が飛んでしまうので相手に伝わる配慮はすると良いです。

また、通例では PR側から Issue側に リンクさせる事が多いです（今回はそこまで徹底はしない予定ですが）z

**Comment by ms2sato** [comment]
Finished
