### ISSUE TITLE
いいね機能

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#49]
ref https://github.com/shuma1020/training_app/pull/48

あるユーザーが気に入ったProductを個別に「いいね」できる機能を作成する。ブランチを作って進めます。

- [x] DB設計（最初にやる。これがやれないなら進められない）
- [ ] 実装

**Comment by ms2sato** [comment]
@shuma1020 パトロンの前にこれ。とりあえずDB設計します。パトロンの時にも 多対多という言葉でアドバイスしていると思います。それができなければ実装進めても思ったように動かないので学習して進める事。

場合によってはこのプロジェクトでやらず、多対多を別のプロジェクトを作って理解してからやること。ムリクリトライアンドエラーしても結果時間がかかる系の内容です。

**Comment by shuma1020** [comment]
@ms2sato 多対多に関しては調べ、下記について理解しました。
- 複数のproductsに対し、複数のusersの関係が存在する場合、多対多の関連付けとなる
- 多対多において中間テーブルが必要となる。(今回はagentとおいた)　patronになるのはあくまでもuserである。
- イメージとしては中間テーブルを通して、お互い関連しあっている。なのでproductsテーブルもuserテーブルも中間テーブルであるagentsをもつ(has_many :agents)
- agentsテーブルは二つのテーブルに従属している。(belongs_to :product  belongs_to :user)(product とuserの外部キーを保持している user_id product_id)

**Comment by ms2sato** [comment]
@shuma1020 ではイイねを作るとしたらどうします？ 上記は伝わっている前提で 変更される内容だけ列挙してくれれば大丈夫です。

**Comment by shuma1020** [comment]
@ms2sato 
いいねの条件によりますが、基本的な構造自体は同じかと推測します。
いいねの条件とは
-　1user 1product　1回だけであれば、validatesなどで条件をつける。

**Comment by ms2sato** [comment]
@shuma1020 今望まれている答え。「設計」なんで明瞭に出す。条件については一旦それで良いですよ。

- 変更されるテーブルとその内容
- 新規作成されるテーブルとその内容
- アソシエーションの付け方

**Comment by shuma1020** [comment]
@ms2sato 下記について、パトロンを作るのといいねをすることの違いを列挙してくださいという意味で捉えたのですが、いいね機能を作るにはどのようなDB設計が必要かということですか？
> 上記は伝わっている前提で 変更される内容だけ列挙してくれれば大丈夫です。

**Comment by ms2sato** [comment]
@shuma1020 YESです！どのような設計にするかを確認してからコードを書いて欲しいのです。なので、「設計の成果物」求められています。

**Comment by shuma1020** [comment]
@ms2sato 
- ProductテーブルとUserテーブル
- Likeテーブル　(product_id, user_id)
- Likeモデル(belongs_to product ,belongs to user)　Userモデル,Productモデル(has_many likes)

**Comment by ms2sato** [comment]
@shuma1020 概ねOKです！テーブル名はモデル名から類推して返信します

> ProductテーブルとUserテーブル

テーブルという意味ではこの2テーブルには変更が無いのでは無いですか？なにか変更の影響を受けるという意図か教えてください。

> Likeテーブル　(product_id, user_id)

Likeテーブル　(product_id, user_id) を新規作成する のような表現が良いですね。

**Comment by shuma1020** [comment]
@ms2sato 特に変更はないと思われます。承知しました！

**Comment by ms2sato** [comment]
@shuma1020 そしたら実装してみますかー。一度やっている様子なのであまり時間かからない想定です。

**Comment by shuma1020** [comment]
@ms2sato PR作ってやってみます！

**Comment by ms2sato** [comment]
fin
