### ISSUE TITLE
Likeのバリデーションを修正する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#53]
https://github.com/shuma1020/training_app/pull/50/files#r359776772

上記のコードの部分について、気持ちは伝わるのですが、現場でよく使う方法で実現しましょう。下記の項目を読んで、メソッドを指定する方法を利用します。

https://railsguides.jp/active_record_validations.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89

また、中身のコードが puts になったりしているとバリデーションエラーにできません。上記のドキュメントでは、例として以下のような方法を使っています。

```rb
errors.add(:expiration_date, ": 過去の日付は使えません")
```

もしもerros.addについて理解が足らない様子だったら、https://railsguides.jp/active_record_validations.html の最初の方から読んでみると良いです。

**Comment by shuma1020** [comment]
@ms2sato 下記のようにしてみました！
```
validate do
        unless user && user.liked_for?(product)
            errors.add(:base, "いいねはできません！")
        end
    end
```

**Comment by ms2sato** [comment]
@shuma1020 

> メソッドを指定する方法

validate の引数に メソッド名をシンボルで入れる方法があるので、その方法にしてください。こちらの方がよく使われるので。

中身に関しては書いてくださった内容で一旦OKです。

**Comment by ms2sato** [comment]
https://github.com/shuma1020/training_app/issues/54#issuecomment-568449030
多分これはこのIssueの作業で起きたかな？

**Comment by shuma1020** [comment]
@ms2sato 今エラー確認いたしました。そのように思われます！

**Comment by ms2sato** [comment]
LGTM!
