### ISSUE TITLE
products#liked は、mypage配下に移動する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#54]
自分のアクションの結果を見るという観点なので mypage 配下に移動しましょう。

**Comment by ms2sato** [comment]
@shuma1020 
![image](https://user-images.githubusercontent.com/627817/71355417-51886d80-25c2-11ea-98a9-04f830179d7e.png)

エラーになってしまうのでみてください。

**Comment by shuma1020** [comment]
@ms2sato validatesのsが余計だったと思われます！

**Comment by ms2sato** [comment]
@shuma1020 修正点バッチリです。Likeのバリデーションをテストできていなかった為だと思います。

作業一つしたら、その動作を必ずテストするようにしましょう。自分のやった仕事が正しいかを自分で証明して進んでください。そうしないと、他メンバーが @shuma1020 のバグをデバッグしないといけなくなるので人の時間を奪います。

**Comment by ms2sato** [comment]
内容は終わったのでClose
