### ISSUE TITLE
カードレイアウトを整える（/products）

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#56]
# 補足
カードのUIをキチッとbootstrapの流儀に沿ってやると良いと思うので、改めてIssue化しました。画像を扱っているCardのやり方が定義されているので、それに合わせます。bootstrapという道具の使い方を調べて実践するのがこのIssueでやるべきことです。

- https://getbootstrap.com/docs/4.3/components/card/

これを確認すれば、下に出している画像の雰囲気にあまり苦労せずに合わせられるはずです。

以下、以前の内容を再掲。

# やるべき内容

こんな感じを目指すイメージでやってみましょうか。

![image](https://user-images.githubusercontent.com/627817/70324677-7c10c180-1873-11ea-828f-2cebdd8b6b16.png)

### 一覧で出す項目
- タイトル
- 目標価格
- 状態
- お返しの数（これは学習のため）

**Comment by shuma1020** [comment]
@ms2sato eachメソッドを用いているので、結構レイアウトが崩れてしまって苦戦中です

**Comment by ms2sato** [comment]
@shuma1020 each でレイアウトが崩れてしまうということは、HTMLの開始タグと閉じタグが対応できていない可能性が高いです。インデントをうまく活用するなどして、どういう単位でタグを出力するのかを意識しながら進めると進めやすいと思います。

また、最初からたくさんのタグを入れるのを一度やめてみて、シンプルなタグ構成からスタートし、だんだん肉付けしていくのもオススメの手段です。

**Comment by shuma1020** [comment]
@ms2sato 丁寧に徐々に肉付けしていったら、少しづつ理想に近づいてきました。bootstrapで補完できないところはcssを追加に書いているのですが、その方向性でよろしいでしょうか？
<img width="335" alt="スクリーンショット 2019-12-22 21 23 01" src="https://user-images.githubusercontent.com/56459339/71321753-6ea93780-2501-11ea-8a7a-00fe1a06c393.png">

**Comment by ms2sato** [comment]
@shuma1020 おお！とてもいい感じになってきましたね。CSSの追加は問題ないです。bootstrapで用意されている道具があればそれを使う方が望ましいので、調べてみてから無ければ追加が良いです。

また、bootstrapとアプリケーションのcssは明瞭に分けたいので
`/app/assets/stylesheets/mypage/products.scss` に入れましょうか。ここのファイル分けは色々流儀がありますが、今回はこだわり過ぎずに適度にやると良いです。

**Comment by ms2sato** [comment]
@shuma1020 あと、丁寧なスクショ貼りもとても良いです。実際の仕事でも報告でよく行います。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！

**Comment by ms2sato** [comment]
@shuma1020 カッコいい見た目になったのは `/mypage/products` だったんですね。
オーダーとしては `/products/` の方だったので気をつけましょう。こうやって URLのパスを指定して作業場所を明示することは良くあるので、汲み取れるようになっていってください。

今回は練習でもあるので 修正は求めませんが、あとでお願いするかもです。

**Comment by ms2sato** [comment]
一旦IssueとしてはCloseしますね。
