### ISSUE TITLE
ProductとRewardをネストする

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#57]
ref https://github.com/shuma1020/training_app/issues/8

改めてIssueを作成し直しました。
mypage の下の内容だけ ProductとRewardのネスト対応をしましょう。

**Comment by shuma1020** [comment]
@ms2sato 
mypageとRewardのnestはできたと思きました。ただ今回はMypageとすでにネスト化されているProductとRewardをネスト化するということだと思うので、controllerとactionのイメージはmypage/products/rewards#indexなのですが、実際はそうならずmypage/rewards#indexになっています。
```rb
namespace :mypage do
    resources :products do
      get "liked", on: :collection
      patch "unlike", on: :member
      resources :rewards, only: [:index]
    end
    resources :rewards
  end
```

### 直面している課題の整理
- 三段階のネスト化ができない(Mypage/Product/Reward)
  - URLはイメージ通りのものが生成できても、コントローラーができない。下記のURLは同じアクションを呼んでしまう
```rb
mypage_product_rewards GET    /mypage/products/:product_id/rewards(.:format)                                           mypage/rewards#index

mypage_rewards GET    /mypage/rewards(.:format)                                                                mypage/rewards#index
```

**Comment by shuma1020** [comment]
@ms2sato 
既にこのように場合分けされていた。このことから深いネストはアクションの中で場合分けすることで成立するのではないかと推測する
```
def index
    if params[:product_id]
      p "#####"
      p params
    @product = Product.find(params[:product_id])
    @rewards = @product.rewards
    else
      @rewards = Reward.all
    end
  end
```

**Comment by ms2sato** [comment]
@shuma1020 

> controllerとactionのイメージはmypage/products/rewards#indexなのですが、実際はそうならずmypage/rewards#index

コントローラー・アクションについては `mypage/rewards#index` で進めて良いですよ。resourcesをネストさせても、コントローラーの構成はフラットなままです（指定すれば親子関係作れますが、それは応用的な考え方で良いです）。

URLとの関係としては 以下のような法則の組み合わせで良いということになります。

- `mypage/products/:product_id/rewards` : `mypage/rewards#index`
- `mypage/products/:product_id/rewards/new` : `mypage/rewards#new`
- `mypage/products/:product_id/rewards/:id/edit` : `mypage/rewards#edit`


https://github.com/shuma1020/training_app/issues/57#issuecomment-568180816
の場合分けは @shuma1020 が行なったものだと思いますが、このような場合分け無しにスンナリ動く筈です。

念の為ですが、 mypage 階層はネームスペースの機能で実現しており、resourceのネストではありません。

**Comment by ms2sato** [comment]
@shuma1020 修正をお願いしようと思ったけれど、理解の確認をして理解できているなら今のコードの方針でも良いと思い直しました。

> controllerとactionのイメージはmypage/products/rewards#indexなのですが、実際はそうならずmypage/rewards#index

コントローラー・アクションについては `mypage/rewards#index` で進めて良いです。今の方針で良いです。
Railsの仕組みとしては、resourcesをネストさせても、コントローラーの構成はフラットなままです（指定すれば親子関係作れますが、それは応用的な考え方で良いです）。

https://github.com/shuma1020/training_app/issues/57#issuecomment-568180816
の場合分けは @shuma1020 が行なったものだと思いますが、理想ではこのような場合分け無しにスンナリ動く筈です。

念の為ですが、 mypage 階層はネームスペースの機能で実現しており、resourceのネストではありません。

## 理解度確認の質問
示してくれている routes.rbの一部には rewardsが2回登場していますが、これの意図を教えてください。

```rb
  namespace :mypage do
    resources :products do
      get "liked", on: :collection
      patch "unlike", on: :member
      resources :rewards, only: [:index]
    end
    resources :rewards
  end
```

**Comment by shuma1020** [comment]
@ms2sato 
>理想ではこのような場合分け無しにスンナリ動く筈です。

つまり下記のURLらは同じアクションかつ場合分けすることなく動くということですね？ちなみに場合分けした理由としてproduct_idがパラメーターとして渡されているかいないかにあります。
```
mypage_product_rewards GET    /mypage/products/:product_id/rewards(.:format)                                           mypage/rewards#index

mypage_rewards GET    /mypage/rewards(.:format)  
```

### 理解度確認の質問

rewards#indexのみproductsとネスト化の関係にあれば良いかと思い、そのほかのアクションに関してはmypageのみとのネスト化にいたしました。

**Comment by ms2sato** [comment]
@shuma1020 

> つまり下記のURLらは同じアクションかつ場合分けすることなく動くということですね？

この質問ちょっと答えにくいので、正面からの回答はちょっと後に回させてください。ごめんね。

ただ、仕様を以下のように固定した方が進めやすそうなので、こちらを提示します。読んでいただいてゴール感がわかりにくいようだったら質問をください。

## /mypage/products/:product_id/  配下について

ここはProductを新たに作成したり、その作成したProductにRewardを追加したりなどの「自分が提供したProductの作成や編集処理」を示すこととします。

- `/mypage/products` は「自分が作成したproducts」が対応する
  - `/mypage/products/:id` にはProductの各カラムの情報と共に、既に作成したRewardが表示されるものとします（つまり rewards#index 的な動作はここに入っている。newやeditへのリンクもこの画面にあって良いです）。
- `/mypage/products/:product_id/rewards/` には、以下のアクションが可能とする
  - GET `/mypage/products/:product_id/rewards/new`: 対象の productに新しいrewardを追加する画面を表示する
  - POST `/mypage/products/:product_id/rewards`: 対象の productに新しいrewardを追加する処理を行う
  - GET `/mypage/products/:product_id/rewards/:id/edit`: 対象の productに新しいrewardを編集する画面を表示する
  - PATCH `/mypage/products/:product_id/rewards/:id`: 対象の productの指定のrewardを更新する処理を行う

## /mypage/rewards 配下について
こちらは削除してしまって良いです。動かなくてOKです。

**Comment by ms2sato** [comment]
![image](https://user-images.githubusercontent.com/627817/71354968-e5f1d080-25c0-11ea-96ce-56c53c60b6b5.png)

@shuma1020 Cardのサイズが変わっているのを理解しました。あと、画像がリンクになっていて編集画面に飛べるんですね。操作できました。OKです。その上で下記を対応してみてください。

### 1. formの内容について

![image](https://user-images.githubusercontent.com/627817/71355169-98299800-25c1-11ea-9250-633d20c98357.png)

### 2. /products/:id の画面について
![image](https://user-images.githubusercontent.com/627817/71355284-e50d6e80-25c1-11ea-9478-365e168dbe11.png)

編集作業は基本的に mypage から所有者が行うイメージにしていきましょう。 `/products/` は見るだけの用途です。

**Comment by ms2sato** [comment]
@shuma1020 今回 edit のリンクを削除したと思いますが、これに関連して消せるものを考えましょう。

- [ ] routes.rb の設定で入ることができなくなるアクションを考えて不要なルーティングが作成されないようにする。
- [ ] Controllerにあるアクションで呼び出されないものを削除
- [ ] 呼び出されないviewの削除

**Comment by ms2sato** [comment]
できてそうなのでClose
