### ISSUE TITLE
フォームの入力が空でも登録できてしまうのを抑制しましょう

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#6]
何も入力しなくても登録できてしまうのを防ぎたいです。さて、どうしたら良いでしょうか。
一旦条件としては以下にしましょう。

# Product
- title: 必須
- price: 必須
- description: 必須

# Reward
- title: 必須
- description: 必須
- price: 必須

**Comment by shuma1020** [comment]
`class Reward < ApplicationRecord
    belongs_to :product
    validates :title, presence: true
    validates :price, presence: true
    validates :description, presence: true
end`

**Comment by shuma1020** [comment]
`class Product < ApplicationRecord
    has_many :rewards
    validates :status, presence: true
    validates :title, presence: true
    validates :price, presence: true
    validates :description, presence: true
end
`

**Comment by ms2sato** [comment]
ここにコードは書かなくて大丈夫だけど、できてましたー。Closeします！
