### ISSUE TITLE
/mypage/products/new の内容が左に寄りすぎ

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#62]
![image](https://user-images.githubusercontent.com/627817/71356015-3e769d00-25c4-11ea-9150-f63897518561.png)

左のマージンが入るようにしてあげて欲しいです。また、これを各画面で気をつけて入れなくても大丈夫なように共通化してしまいましょう。

**Comment by shuma1020** [comment]
@ms2sato 「左に寄りすぎ」に関しては他の画面ではdiv class="container"をつけることで調整しており、この画面はそのつけ忘れであるため、他のと同様containerをつけて対応したのですが他の方法の方がよろしいでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 

> 他の方法の方がよろしいでしょうか？

そうです。私が以下のように書いているのはその方法では無いことを示しています。

> 各画面で気をつけて入れなくても大丈夫なように共通化してしまいましょう。

方法の提案くださいな。どうやると良いでしょうか。
`div class="container"` はbootstrapを使っている以上全ての画面で必要ではないでしょうか？

**Comment by shuma1020** [comment]
@ms2sato  layouts/applicationのbodyのcssにmarginを入れる
containerを入れた場合、左寄せは解決すると思うのですが上記の方法でいちいち気にしなくても済むと考えます

**Comment by ms2sato** [comment]
@shuma1020 レイアウトファイルを利用してできるという提案で十分です。

具体的な対応は`<div class="container">` をレイアウトで指定しておき、その下の階層では入れない、という形で良いと思います。bootstrapを全ての画面で適用するはずなので、必要になります。
よろしくお願いします。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！

**Comment by ms2sato** [comment]
@shuma1020 作業した内容は確認しましたが、インデント適切にしましょう。

**Comment by ms2sato** [comment]
適切に直ってました！Closeしまーす。
