### ISSUE TITLE
「パトロンになる」機能を実装する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#63]
ref #36

ちょっと大きめの仕様を一度試したいので、以下のような仕様を作りました。
目を通してもらって、もしも質問あれば対面でやりましょう。

https://cacoo.com/diagrams/TOsxrMjbcZjn6K1p/1F118

**Comment by shuma1020** [comment]
@ms2sato 
/products/:id/patrons/newと指定されていたのですが、/products/:product_id/patron/newとはまた異なりますか？
```
resources :products, only: [:index, :show] do
    collection do
      get "draft"
      get "release"
    end
    resources :patron
    patch "like",  on: :member
  end
```

**Comment by shuma1020** [comment]
@ms2sato routesじっくり見たらアクションとコントローラーが違う気がしてきたので見直します

**Comment by shuma1020** [comment]
@ms2sato patronはUserテーブルとProductテーブルの中間テーブルだと思うのですが、中間テーブルが下記のようにコントローラーになることはおかしいのかと考えます。
例えばlikeの場合ProductsController#likeであり、LikesControllerは存在しませんでした。しかし下記のコードはPatronsController#newなどをさしているので違和感があります。

ただ今回の場合仕様に/products/:id/patrons/newがあり、Patronディレクトリのnew.html.erbが必要、つまりPatronsController#newは正しいのかとも思われます。

前者と後者二つの考えで悩んでいます

```rb

                      product_patrons GET    /products/:product_id/patrons(.:format)                                                  patrons#index
                                      POST   /products/:product_id/patrons(.:format)                                                  patrons#create
                   new_product_patron GET    /products/:product_id/patrons/new(.:format)                                              patrons#new
                  edit_product_patron GET    /products/:product_id/patrons/:id/edit(.:format)                                         patrons#edit
                       product_patron GET    /products/:product_id/patrons/:id(.:format)                                              patrons#show
                                      PATCH  /products/:product_id/patrons/:id(.:format)                                              patrons#update
                                      PUT    /products/:product_id/patrons/:id(.:format)                                              patrons#update
                                      DELETE /products/:product_id/patrons/:id(.:format)                                              patrons#destroy
                                      GET    /products/:id(.:format)                                                                  products#show
```

**Comment by ms2sato** [comment]
@shuma1020 

> 中間テーブルが下記のようにコントローラーになることはおかしいのか

これに関してはNOです。実際のシステムで単純に中間テーブルだからコントローラーにならないというルールは無いです。意味のあるテーブルなら全部コントローラーになる可能性を持っていますよ。

入れてくれたroutesだと

> /products/:product_id/patrons/new

を利用するで大丈夫です。私のcacooの内容が間違えていると思って良いです。すまぬ。

**Comment by shuma1020** [comment]
@ms2sato そうしましたら下記の方向性で考えていきたいと思います！
>今回の場合仕様に/products/:id/patrons/newがあり、Patronディレクトリのnew.html.erbが必要、つまりPatronsController#newは正しいのかとも思われます。

承知しました！

**Comment by shuma1020** [comment]
@ms2sato  PatronsController#newを作りました。そしてそこにフォームを作るという方法で作業を進めているのですが、うまくpatrons#createのパスを作ることができません。
これだと　product_patrons_product_pathになってしまいます。目指しているのはproduct_patrons_path method: postです。
```rb
<%= form_with(model: [:product_patrons, @product], local: true) do |f| %>
<div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, class:"form-control" %>
  </div>

<% end %>
```

**Comment by shuma1020** [comment]
@ms2sato 
patronになるのはproducts#patron postでいいのではないかと思い下記のように修正を加えました
```
resources :products, only: [:show] do
    resources :patrons, only: [:index]
    patch "patron",  on: :member
  end
```

**Comment by shuma1020** [comment]
@ms2sato product_idがパラメーターとして欲しいので、やはりnewアクションは下記でいいのかと推測しています。Mypage::ProductsController#newなどのnewを参考にして考えていたのですが,
今回はそのnewアクションとは違いproduct_idが必要です。
```rb
def new
    @product = Product.find(params[:product_id])
  end
```

**Comment by shuma1020** [comment]
> @ms2sato
> patronになるのはproducts#patron patchでいいのではないかと思い下記のように修正を加えました.。ただ今回の場合編集は不可、つまり新たに作る場合のみを想定するべきなので、patchのところをpostにするべきなのかとも思い、試したのですがうまくパスを渡せません。(likeは新規いいねの場合もpatchだったのでpatchの可能性も捨てきれない。)
> 
> ## 解決しなくてはいけないこと
> form_withのパスがPatronsController#newを@Product = Product.newにするとpatron_productsになってしまう。products#patronのパスはpatron_productで単数。
> 
> ```ruby
> resources :products, only: [:show] do
>     resources :patrons, only: [:new]
>     patch "patron",  on: :member
>   end
> ```
> 
> patchバージョン
> PatronsController#new
> 
> ```ruby
> def new
>     @product = Product.find(params[:product_id])
>     @rewards = @product.rewards
>   end
> ```
> 
> postバージョン
> PatronsController#new
> 
> ```ruby
> def new
>     @product = Product.new(product_params)
>   end
> ```
> 
> patchバージョンで行うと下記のフォームはちゃんとpatron_product_pathを呼ぶのですが、postバージョンにする(@Product = Product.newにする)とpatron_products_pathになってしまいうまく呼んでくれません。
> 
> ```ruby
> <%= form_with(model: [:patron, @product], local: true) do |f| %>
>   <div class="field">
>     <%= f.label :price %>
>     <%= f.number_field :price, class:"form-control" %>
>   </div>
>   <div class="actions">
>     <%= f.submit class:"btn btn-primary" %>
>   </div>
> 
> <% end %>
> ```

そもそもProductテーブルのpriceカラムではなく、Userテーブルで新たに寄付金というカラムを作らなくては(12/25 21:45)

**Comment by shuma1020** [comment]
@ms2sato 
3時間前にここに書いてから色々進展したので整理します。(以前の質問を消して方がお手を煩わないかと思うのですが、軌跡として記録しといた方が良いと思い残しておきます。)

- 応援金額はUserテーブルのデータ
    -  donationというカラムを作りました
- patrons#newのformで送信され、受け取るデータはdonation(params[:donation])

下記のフォームからはパラメーターとしてdonationが受け取れる。
```
<%= form_with url: patron_product_path(@product, @user)do |f| %>
  <div class="field">
    <%= f.label :donation %>
    <%= f.number_field :donation, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>
```

**Comment by shuma1020** [comment]
@ms2sato 
ブランチを変えて再度チャレンジします。
DB設計
- patronテーブル(中間テーブル)(user_id, product_id, donation)を新規作成する
- Userテーブル(has_may :patrons, has_many :donated_products),Productテーブル(has_many :@patrons, has_many :funders), Patronテーブル(belogns_to :user , product)

**Comment by shuma1020** [comment]
@ms2sato ブランチを変えたはずなのにpatronテーブルが存在するのはなぜでしょう？searchでpatronとやったらdeleted状態のpatronモデルが反応したのですが、そこに原因があるのでしょうか
SQLite3::SQLException: table "patrons" already exists

**Comment by ms2sato** [comment]
自分で解決できて何よりです。今patron2のブランチと、masterはDBの内容が違うので注意してください。

**Comment by shuma1020** [comment]
@ms2sato 
注意というのは何かこれはしてはいけないというのはありますか？それとも忘れないようにしておく程度で大丈夫ですか？

**Comment by ms2sato** [comment]
@shuma1020 してはいけないことがあるわけでは無いです。

- masterでデータ修正をDBに反映すると、Sqliteのデータが変更されます
- patron2でデータ修正をDBに反映すると、postgresのデータが変更されます

なにかうまく動かない時に masterならうまく動くかどうかを比較対象にしたりしますが、今回はDBが違うので同じ動きにならない可能性がありますし、データをどちらかでいれたももう一方には反映されません。そういう理解をしておいてください。

**Comment by shuma1020** [comment]
@ms2sato 承知いたしました！

**Comment by ms2sato** [comment]
一旦Close
