### ISSUE TITLE
データが全部無い場合にログインするとマイページに入れない

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#68]
![image](https://user-images.githubusercontent.com/627817/71540322-3a63ca00-298c-11ea-885f-59268b5f5b73.png)

patron2をいじろうと思った時に出会ったもの。masterで内容をpushしてから、patron2側が変更を取り込むと良いでしょう。

**Comment by shuma1020** [comment]
@ms2sato エラーには対応したのですが、頂いたアドバイスをいまいち理解ができませんでした。

> patron2をいじろうと思った時に出会ったもの。masterで内容をpushしてから、patron2側が変更を取り込むと良いでしょう。

**Comment by ms2sato** [comment]
@shuma1020 

エラーが発生した場合、以下のようなことを考えます。

1. 「masterでも起こるのかどうか」
2. 1がYESなら、これは現在のサービスの問題なのでmasterで修正します（適切にやるならバグを修正するブランチを作ってmasterへマージします）。修正しないと他のブランチでも発生して困るし、masterからこれから分岐するブランチでもバグを抱えているのでマイナスが大きいためです。
  - この時の一般的な対応  masterを修正し、masterを作業ブランチ（ここではpatron2）へマージします
3. 1がNOなら、作業ブランチだけの問題なので、作業ブランチの中だけで修正します。
  - 自分のブランチで発生したバグを自分のブランチで修正するので普通です。

patron2で修正してマージする、というのは patron2ブランチの作業がなかなかマージできない場合にはmasterが修正されないのでリスクを抱え続けます。

私の書いた内容はそういう背景です。

**Comment by shuma1020** [comment]
@ms2sato なるほど！丁寧な説明ありがとうございます！よく理解できました。

**Comment by ms2sato** [comment]
おわってたのでclose
