### ISSUE TITLE
[木曜]vendor/bundle のディレクトリを gitの管理から外す

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#7]
このディレクトリは共有しない方が良いものなので、gitの管理から外して、GitHubに上がらないようにしましょう。

**Comment by shuma1020** [comment]
git rm -r --cached vendor/bundle/

**Comment by ms2sato** [comment]
@shuma1020 
https://github.com/shuma1020/training_app/tree/master/vendor/bundle/ruby/2.6.0

ここに内容が入っているうちはgitから消去できていないので確認してみてくださいな。

**Comment by shuma1020** [comment]
shuma$ git rm -r vendor
rm 'vendor/.keep'
消えないので木曜にトライ
