### ISSUE TITLE
[調査] form_with local: true について調べる

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#70]
ref #66 
ある程度までしか把握できないと思いますが、一度調査しましょう。その上でフォロー入れます。ブラウザでできる Ajax という機能と密接に関係しているので以下の2つを調べましょう。

1. Ajaxとは何か調べる
2. form_withのlocal: true で何が起こるのかを調べる。

調べた結果はこのIssueにコメントで記してください。

**Comment by shuma1020** [comment]
@ms2sato 
- ajaxの根幹はjavascriptによって作られている。ajaxにおいて使用される技術を使えば、ページを更新することなくページの内容だけを入れ替えられるので、使い方によってはより快適なウェブページを作成できます。
https://www.sejuku.net/blog/28967
- local: trueがない場合、Rails 5ではAjaxによる送信という意味になります。ふつうにHTMLとしてフォームを送信する場合にlocal:trueが必要となります。

**Comment by ms2sato** [comment]
対面で会話済み。Close
