### ISSUE TITLE
[マイページ]patron情報の一覧を作成する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#72]
参考: https://cacoo.com/diagrams/TOsxrMjbcZjn6K1p/1F118

**Comment by shuma1020** [comment]
@ms2sato 幹となるところはできました。デザインはこれからです！

**Comment by shuma1020** [comment]
@ms2sato それっぽいデザインはbootstrapの力を借りできたのですが、タイトルが上すぎる気がします。そのため調整を試みているのですが、この場合cssで追加で書くのがいいのか、bootstrapで調整するのがいいのかどちらの方が良いのでしょうか？bootsrapで調整した方が、他のデザインを崩さずにできるのでいいのかと推測しています。ただ試したのですが、いまいち中央にセッティングできません。
```
<h5 class="card-title align-middle">
```

**Comment by ms2sato** [comment]
@shuma1020 デザイン拝見しました。この内容だと、 cardよりも gridでやった方が筋が良さそうかな。cardっぽいレイアウトにあまりならない感じがしています。

今の方針で cardで進めていくならば、bootstrapのcardのルールを今一度見直すと良いです。例えば、ちゃんとできている右側の内容だと、`card > card-body > card-text` の親子関係が適切に対応しているからうまくマージンが当たっています（これは Chromeの開発者ツールで見れるので試してください）。

bootstrapのようなCSSが不自然な時に最初に考えるべきは、適切な利用方法で使えているかなので、その辺りを確認するのが最初にできるアクションでしょう。

**Comment by ms2sato** [comment]
@shuma1020 わかっていそうですが、デバッグのコードがコントローラーに残っているので消しましょう。内容は大丈夫そうです。

**Comment by ms2sato** [comment]
Closed
