### ISSUE TITLE
/product/:id にて「自身が既にパトロンである場合」のUIを整える

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#73]
https://cacoo.com/diagrams/TOsxrMjbcZjn6K1p/1F118

対象の rewardの表示を色づけしましょう。最初に「どのような実装をする予定か」を @ms2sato と打ち合わせてからやりたいので、このIssueにコメントしてください。

**Comment by shuma1020** [comment]
@ms2sato 
まず対象のrewardを選ぶところを実装する予定です。つまりrewardに選択肢を追加する必要があります。
1. donationが何円以上ならこのrewardと決める
2. PatronとRewardの中間モデルが必要

**Comment by ms2sato** [comment]
@shuma1020 拝見しました。DBに適用されたrewardを保存する手法ですね。基本方針としては良いと思います。

2番についてですが、そもそも `Patron`と `Reward` の中間モデルが必要と考えている根拠ってありますか？多対多になったりする仕様で考えているでしょうか？頭の中に描いているものをもう少し伝えて欲しいです。

> Productモデルを中間モデルとして利用する

これについても根拠を示してもらえると嬉しいです。注意して欲しいのは、アソシエーションの辿り方は、そのアソシエーションの意味付けによって考えます。「たどり着ければ何でも良い」と言うものではないのでそのあたり解説ください。

**Comment by shuma1020** [comment]
@ms2sato 
RewardはPatronモデルのdonationによって選択されるものが変わってきます。例えばdonation<1000の時reward1, 1000<donation<2000 の時　reward2などと。そこで中間モデルにdonationとrewardの組み合わせを定義したものを置こうと考えていました。しかしそれはRewarに定義できるのではないかと思い直し、必要ないのではないかと考えています。
ここで考えないといけないのはRewarモデルにおけるrewardの選択肢をどのように儲けるかであると考えます

**Comment by ms2sato** [comment]
@shuma1020 

> RewardはPatronモデルのdonationによって選択されるものが変わってきます

その通りですね。考え方は間違い無いです。Patronが1つあれば、選択されたRewardも1つある、という想定ですね。私も同じ考えです。

> それはRewarに定義できるのではないか

Rewardに、選択されたRewardをいれてしまうという意味ですか？ちょっと私が @shuma1020 の考えを推察できません。

今の課題は「donationの金額によって、選択されるrewardが変わり、その時選択されたrewardの格納場所を考えている」という事だと思いますが、同じ課題に立ち向かっている、という理解で大丈夫ですか？

個人的には中間テーブル無くてもできる事だと思っているのですが、新しいテーブルを作らないと難しいですかね。所有する値の単位が一緒なら基本的には一緒にできるはず。

例えば整理すると以下のようにそれぞれのモデルがあります。

- Reward: Productにぶら下がって複数存在できる。
- Patron: Productと支払いUserの関係として、ProductとUserの組み合わせが被らない条件で複数存在できる

**Comment by shuma1020** [comment]
@ms2sato 中間テーブルは必要ないかと考えています。
> Rewardに定義できるのではないかと思い直し、必要ないのではないかと考えています。

下記の関してもそうですが、まず「donationがいくらならどのreward」という基準をどこに作ればいいのかということを考えています
> 今の課題は「donationの金額によって、選択されるrewardが変わり、その時選択されたrewardの格納場所を考えている」という事だと思いますが、同じ課題に立ち向かっている、という理解で大丈夫ですか

**Comment by ms2sato** [comment]
@shuma1020 これ、オンラインでテキストで誘導するの無理だと思うので対面にします。

**Comment by shuma1020** [comment]
@ms2sato 承知しました。

**Comment by ms2sato** [comment]
一旦大丈夫そうなのでClose
