### ISSUE TITLE
自分がまだパトロンになっていないのに、誰かがパトロンになると「パトロンになっている」という表示になってしまう

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#74]
![image](https://user-images.githubusercontent.com/627817/71775322-42da8700-2fc2-11ea-9fac-d0aad65b7bdb.png)

**Comment by shuma1020** [comment]
@ms2sato 
current_userとの関係性が明記されていませんでした。整理するとcurrent_userがこのプロダクトでなったパトロンを表示させればいいと思うので、今トライしています。(方向性の確認)
```rb
Patron.find_by(product_id:18,user_id:3)
  Patron Load (0.8ms)  SELECT "patrons".* FROM "patrons" WHERE "patrons"."product_id" = $1 AND "patrons"."user_id" = $2 LIMIT $3  [["product_id", 18], ["user_id", 3], ["LIMIT", 1]]
=> #<Patron id: 10, user_id: 3, product_id: 18, donation: 3333, created_at: "2020-01-05 06:23:17", updated_at: "2020-01-05 06:23:17">
```

**Comment by shuma1020** [comment]
@ms2sato 
少し苦戦しましたが、できました。
@patronを言葉の通り「current_userがこのプロダクトでなったパトロンを表示」を再現しました。他の方法も考えました。例えば、@patron = Patron.find_by(user_id: current_user.id)にし、@productを@product = @patron.product.find(id: params[:id]にするなどです。ただこれは結論から言うとshowアクションにおいてはやめておくべきだと判断しました。と言うのも、このページではすでに@productが定義されており、それを元に表示されているものがあるからです。
```rb
 def show
    @rewards = @product.rewards
    @patrons = @product.patrons.all
    @patron = Patron.find_by(user_id: current_user, product_id: params[:id])
  end
```

**Comment by ms2sato** [comment]
@shuma1020 返信遅れてしまいましたが、そもそもの推察などはドンピシャです。解決までの流れはとても良かった。

最後の考え方についてですが、`@product` が先に検索されているから、その結果を利用して下記のようにする考えがあります。これは推奨される書き方です。

```rb
@patron = @product.patrons.find_by(user_id: current_user)
```

さらに、情報がUserによって絞られることが伝わりやすいとさらに良いです。なぜかと言うと「自分のpatron情報である」ということがわかりやすくすると「他人の情報が表示されてしまう」のようなバグが起きにくくできるためです。と言うわけで下記の書き方ができれば模範回答でした。

```rb
@patron = current_user.patrons.find_by(product: @product)
```

ちなみに、アソシエーションをモデルに適切に書いてあれば、 find_byの引数でproduct_idとしなくても動くので試してみてください。

masterのコードを見ると周辺にデバッグで書いたコードが残っているので、それは消しましょう。一緒に `@patrons` も使われていないので消して良いですね。

**Comment by shuma1020** [comment]
@ms2sato 
なるほど！
ちなみにこの部分(product: @product)の解釈を言葉にするとどのようになりますか？例えば(product_id: params[:id)の場合Patronモデルのproduct_idはパラメーターで受け取ったものとするみたいになると思います。
(product: @product)に関していうと、Patronモデルがアソシエーションしているproductは@productとする。みたいになるのかと考えています。

あとここの部分(user_id: current_user)もなぜcurrent_user.idが省略できるのか疑問です。どちらともエラーは出ないので省略できるものであるというのはわかるのですが、current_userをでバックしたものとcurrent_user.idをデバッグしたものでは出力されるログが異なります。省略できる理由として考えているのが、current_userの先頭がuser_idだからなのではないかです。

**Comment by ms2sato** [comment]
@shuma1020 

`current_user.patrons.find_by(product: @product)` の部分を噛み砕いて示すなら
「ログイン中のユーザーが所有しているpatronからproductアソシエーションが@productであるものを絞り込んで1件取り出す」

ですかね。 @shuma1020 の表現だと逆の表現に思えます。SQLのSELECTは情報を絞り込んで抽出するものなので、そういう表現ができると良いです。あくまでもActiveRecordはSQLを組み立てやすくする道具です。

「productアソシエーションが@productであるもの」という言い方はあまりせず、日常の会話では「productが@productであるもの」のように伝えると思います。

> 出力されるログが異なります

ちょっとわからなかったのでそちらのログを貼ってください。私の手元では同じSQLになると思います。

```
irb(main):012:0> product = Product.last
  Product Load (34.9ms)  SELECT "products".* FROM "products" ORDER BY "products"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<Product id: 4, title: "t", price: 1000, description: nil, created_at: "2020-01-06 11:58:16", updated_at: "2020-01-06 11:58:16", message: nil, status: "release", user_id: 3, image: nil>
irb(main):013:0> current_user= User.last
  User Load (7.6ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<User id: 3, email: "user3@example.com", created_at: "2019-12-28 07:05:26", updated_at: "2020-01-05 04:48:11", name: "user3", role: "normal">
irb(main):014:0> product.patrons.find_by(user_id: current_user)
  Patron Load (10.0ms)  SELECT "patrons".* FROM "patrons" WHERE "patrons"."product_id" = $1 AND "patrons"."user_id" = $2 LIMIT $3  [["product_id", 4], ["user_id", 3], ["LIMIT", 1]]
=> nil
irb(main):015:0> product.patrons.find_by(user_id: current_user.id)
  Patron Load (5.7ms)  SELECT "patrons".* FROM "patrons" WHERE "patrons"."product_id" = $1 AND "patrons"."user_id" = $2 LIMIT $3  [["product_id", 4], ["user_id", 3], ["LIMIT", 1]]
```

> (user_id: current_user)もなぜcurrent_user.idが省略できるのか

これは current_userがActiveRecordで提供されているオブジェクト（Userモデルのインスタンス）である為、 ActiveRecordが current_user.id を暗に呼び出してくれる為だと思います。

例えば (donation: current_user) としても呼び出し自体はされるはず（ただし、 donationの値がuser_idと一致するという内容自体は間違いですが、実行自体は成功させることができます）。

**Comment by shuma1020** [comment]
@ms2sato 
なるほど、下記のは上からcurrent_userで下がcurrent_user.idです。
```
#<User id: 1, email: "user1@example.com", created_at: "2019-12-28 10:47:59", updated_at: "2019-12-28 10:47:59", name: "shuma", role: "normal">
1
```

**Comment by ms2sato** [comment]
@shuma1020 ちょっと貼っていただいた内容の意図が掴めないので先にこちらの話が通じたのか確認したいのですが、下記の内容って理解できたと思って良いですか？

> これは current_userがActiveRecordで提供されているオブジェクト（Userモデルのインスタンス）である為、 ActiveRecordが current_user.id を暗に呼び出してくれる為だと思います。

**Comment by shuma1020** [comment]
@ms2sato 
この箇所は理解できたと思います。それ以降は曖昧です。暗に呼び出してくれるものとして理解すればいいのか、ちゃんとそこには理屈があるのか、どちらなのでしょうか。後者の場合、それを説明できるに至っていません。
> これは current_userがActiveRecordで提供されているオブジェクト（Userモデルのインスタンス）である為

**Comment by ms2sato** [comment]
@shuma1020 その部分の会話を対面でやりましょう。修正対応が終わってたら私にアサインお願いします。

**Comment by ms2sato** [comment]
動作はチェック済み。

**Comment by ms2sato** [comment]
対面確認も終わったのでClose
