### ISSUE TITLE
product_status? についての修正

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#75]
```
    def product_status?
        return true if self.status == "release"
    end
```

これについては以下を考えて修正したいです。

- `product_status?` という名前で意味が通じるか
  - 「product_status がありますか？」のような名前に見えます
- ` return true if self.status == "release"` の内容は冗長である
  - こんなに書かなくて良いはずです。 if で判断して true を返しているので、書いた内容の意味が理解できていれば短く直せるはずです。

**Comment by shuma1020** [comment]
@ms2sato 
status_is_release?と言うのはどうでしょうか？

下記のように修正したのですが、冗長さで言ったらあまり変わらないと思うので確認させていただきたいのですが、return true ifの方に問題があるのか、self.status =="release"の方なのかどちらでしょうか。後者の方も他の書き方ができなかったが模索中です。

```
def status_is_release?
        if self.status == "release"
            true
        end
    end
```

**Comment by ms2sato** [comment]
@shuma1020 `status_is_release?` のイメージなら `status_released?` とかが良さそうかな。状態を示す為に過去分詞にするのはよくやります。実はこの部分はもっと根本的な解決がありますが、今は @shuma1020 が自分で考えて書けたこのメソッドを大事にしたいです。

`return true if` が問題です。 `self.status =="release"` はそのまま残ります。

**Comment by shuma1020** [comment]
@ms2sato 承知しました! 

言葉にすると、self.status =="release" だった時、trueを返すということだと思うのですが、すでに述べているifを使った２つの方法が異なるということでしたらif を使うことなく実装するのでしょうか？何か忘れている気がするのですが思い出せません、、、

**Comment by ms2sato** [comment]
@shuma1020 対面で確認済み。修正したらアサインください。

**Comment by ms2sato** [comment]
@shuma1020 最新のmasterで下記のように書かれていますが、想定通りのコードでしょうか？

```rb
    def status_released?
        return if self.status == "release"
    end
```

**Comment by shuma1020** [comment]
@ms2sato rewardsでその箇所は修正しており、まだマージできていません。

**Comment by ms2sato** [comment]
LGTM!
