### ISSUE TITLE
[調査]メールの送信方法を調べる

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#77]
Railsではメールを送信する仕組みが備わっていますが、それについて調べましょう。参考になるWEBページなどをここに貼ってください。

**Comment by shuma1020** [comment]
@ms2sato 
メールに関してはまだ手をつけていませんが、メイラーの実装という項目が速習実践ガイドに載っていました！
https://railsguides.jp/action_mailer_basics.html

**Comment by ms2sato** [comment]
調査的にはOKの様子。Close。
