### ISSUE TITLE
bootstrapでのマージンとパッディング

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#78]

**Comment by shuma1020** [comment]
@ms2sato 
修正してみました！
https://design-studio-f.com/blog/bootstrap-utilities-spacing/

**Comment by ms2sato** [comment]
@shuma1020 使っている道具的にはOKですね。gridにしては変則的な使い方になったのですが一旦OKとします。

ちなみに `col-sm-6` のように`col-6` ではなくて `col-sm-6` のように書くとどういう作用があるかは説明できますか？

**Comment by shuma1020** [comment]
@ms2sato 全体の画面幅を指定できるという認識です。smであればsmall。

**Comment by ms2sato** [comment]
@shuma1020 

> 全体の画面幅

これって具体的にはどこのことですか？スクリーンショット撮って画面に書き込んでもらって良いですか？

**Comment by shuma1020** [comment]
@ms2sato 
<img width="1439" alt="スクリーンショット 2020-01-13 15 39 46" src="https://user-images.githubusercontent.com/56459339/72236618-0ab6f200-361b-11ea-8d24-556ef5187a63.png">

**Comment by ms2sato** [comment]
@shuma1020 上記の絵が全体幅だとして「どういう作用があるか」を説明できますか？

**Comment by shuma1020** [comment]
r画面のサイズによってレイアウトが変わると認識しております。sm-6であれば画面幅がsmall以上の時6grid。検証ツールで576px以下にした時レイアウトが変わったことからも推測できます。

**Comment by ms2sato** [comment]
@shuma1020 Good。 この動きって機能の名前があったりしますが、そこまで説明できますか？（わからなくても良いですが辿りつけるならとても良いです）

**Comment by shuma1020** [comment]
@ms2sato GridのAuto-layout columnsのことでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 Bootstrapの機能としてはOKですね。HTML/CSSの一般的な呼称だと「レスポンシブ」というものになるので言葉を軽く調べておくと良いと思います。

**Comment by ms2sato** [comment]
いったん終えているのでClose
