### ISSUE TITLE
routingのネストをする

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#8]
https://qiita.com/keisukegdk/items/beb5a62c17278c25c00d

productsとrewards は親子関係があるのでネストをする方が良いです。例えば上記を参考にやってみましょう。

**Comment by shuma1020** [comment]
<img width="1179" alt="スクリーンショット 2019-12-02 9 57 08" src="https://user-images.githubusercontent.com/56459339/69923711-4de55780-14ea-11ea-94ff-c0bcc562d052.png">

記事の通りにネストしてみたのですが、エラーが出てしまいます。そこでRewardsコントローラーを修正する必要があるのではないかと考え、下記の記事を参考に修正したのですがエラー解消ができなかったので質問させていただきます。
[https://sil.hatenablog.com/entry/rails-nested-resource-by-scaffold](url)

**Comment by ms2sato** [comment]
@shuma1020 

> エラーが出てしまいます

この相談をする時には以下3点くらいを一緒に示すようにしてください。

- エラーメッセージの意味を英語から日本語に変えてみた内容
- そこから推察されるエラーの原因
- やってみたこと

「エラーです」だけを見せるのは自分でやれることをやったのか相手に伝わらないので、最初のうちはこれに従うと良いです。

**Comment by shuma1020** [comment]
承知しました。
1.{:action=>......"rewards"}に関して当てはまるルートがありません。かつ必要とされている[:product_id]キーがかけています。

 <%= link_to 'New Reward', new_product_reward_path, class:"header_link" %>で指定している に new_product_reward_pathに:product_id がないのでマッチするルートがないのでURLの生成に失敗した
2.1{:action=>......"rewards"}がないのか
   2 product_idを指定する
3. new_product_reward_path(@product)
new_product_reward_path(params[:product_id])などproduct_idの指定

**Comment by shuma1020** [comment]
Rewardscontroller
def new
    @reward = Reward.find_by(id: paramas[:product_id])
  end

**Comment by shuma1020** [comment]
routingを確認すると
:product_idが二番目に来ている。これが問題なのでは？リサーチ中
` product_rewards GET    /products/:product_id/rewards(.:format)                                                  rewards#index
                                      POST   /products/:product_id/rewards(.:format)                                                  rewards#create
                   new_product_reward GET    /products/:product_id/rewards/new(.:format)                                              rewards#new
                  edit_product_reward GET    /products/:product_id/rewards/:id/edit(.:format)                                         rewards#edit
                       product_reward GET    /products/:product_id/rewards/:id(.:format)                                              rewards#show
                                      PATCH  /products/:product_id/rewards/:id(.:format)                                              rewards#update
                                      PUT    /products/:product_id/rewards/:id(.:format)                                              rewards#update
                                      DELETE /products/:product_id/rewards/:id(.:format)                                              rewards#destroy
                             products GET    /products(.:format)                          `

**Comment by shuma1020** [comment]
データがない故のエラーなのではないかということでrails cデータを追加したがエラー解消ならず

**Comment by ms2sato** [comment]
@shuma1020 確認すべき点のヒント

- Viewを変更した場合、 Railsが出してくれているログ（リクエストがされるとログが書かれています。多分エラーになっている通信があるけれどそれをスクロールで遡ると送った通信もログされているはず）
  - 意図した情報が送られているか確認する。
- ネストは親オブジェクトが既にある前提で、子供を作成したり更新したりする。だから、親は確実にURLにIDを入れられる、という概念。このことを理解して進めること（勘違いしていそうだし、そもそも何をしているのか理解していない可能性が見受けられます。何をしているか理解すること）。
- 親のIDはどういう名前でコントローラーへ送信されるべきか

プログラムの途中でIDを確認したくなったら、 putsや p を使ってログに出しましょう。

**Comment by shuma1020** [comment]
<img width="1150" alt="スクリーンショット 2019-12-02 13 27 21" src="https://user-images.githubusercontent.com/56459339/69930611-847d9b00-1507-11ea-9f7f-d49e23518896.png">
スクロールするとログがあるというのは赤文字で書いてあるRequest以降のことでしょうか？Noneと書いてあるのがヒントに当たるということでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 おっと、WEBの画面の方じゃなくて rails s したターミナルに出てくるのを確認するんだよ。

例えば以下のような表示。これは GET通信が /products にされた時のログです。

```
Started GET "/products" for ::1 at 2019-11-30 20:46:17 +0900
Processing by ProductsController#index as HTML
  Rendering products/index.html.erb within layouts/application
  Product Load (0.1ms)  SELECT "products".* FROM "products"
  ↳ app/views/products/index.html.erb:18
  Reward Load (0.2ms)  SELECT "rewards".* FROM "rewards" WHERE "rewards"."product_id" = ?  [["product_id", 1]]
  ↳ app/views/products/index.html.erb:24
  Rendered products/index.html.erb within layouts/application (Duration: 7.0ms | Allocations: 1470)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 38ms (Views: 34.7ms | ActiveRecord: 0.4ms | Allocations: 7662)
```

今やっているのは先週確認したことと似ています。リクエストしてレスポンスする流れを整えないといけない。

トータルであと1時間くらいやって動かすのが難しそうなら、一回これは置いておいて良いですよ。

**Comment by shuma1020** [comment]
なるほど！これですかね
`ActionView::Template::Error (No route matches {:action=>"new", :controller=>"rewards"}, missing required keys: [:product_id]):
    17:   <h1 class="display-4"><%=link_to 'クラウドファンディング', root_path %></h1>
    18:   <header>
    19:   <%= link_to 'New Product', new_product_path, class:"header_link"%>
    20:   <%= link_to 'New Reward', new_product_reward_path, class:"header_link" %>
    21:   </header>
    22:   <% else %>
    23:   <h1 class="display-4">クラウドファンディング</h1>
  
app/views/layouts/application.html.erb:20

`

**Comment by ms2sato** [comment]
@shuma1020 そうですね！

ここは何かを直すとそれに対応するために別のところを直していかないといけないので、一個修正してエラーが出たからと言って即諦めてはダメです。全体としてどうなっているべきかを自分の頭の中で描かないとダメ。

**Comment by ms2sato** [comment]
@shuma1020 やってみよう！

**Comment by shuma1020** [comment]
@ms2sato 
下記のようなリンクを作りました。
```rb
  <%= link_to 'お返し', new_product_reward_path, class:"nav-link" %>
```
というのもroutesでrewards#newのPrefixがそのようだったからです。
```rb
           new_product_reward GET    /products/:product_id/rewards/new(.:format)                                              rewards#new
```
しかしターミナルでデバッグを確認するとProductsController#newを呼んでいました、つまり今回のissueでエラーが出ていたのはパスがうまく意図したところに飛ばせていないところにあると考えます。ただroutesにはしっかりnew_product_reward_pathでrewards#newと書いてあるので、少し悩んでます。

**Comment by ms2sato** [comment]
@shuma1020 これって、ブランチ作ってやったほうが良い内容だと思うので、ブランチしましょう。まずったら破棄したいだろうし、ここでの変更が他のIssueに影響するとやりにくいですよね（以前作業していたところから察すると変更点多かった気がします）。

**Comment by shuma1020** [comment]
@ms2sato 今nestブランチを作成したので、そこでネストに関しては作業を進めたいと思うのですが、上記の問題がまだ解決できていません。

**Comment by ms2sato** [comment]
@shuma1020 RewardsControllerがネストしない型で通信が成功する、という話であればその仕様なので問題ない、と回答しますが、そういう話で合ってますか？

> ただroutesにはしっかりnew_product_reward_pathでrewards#newと書いてあるので、ネスト化自体はうまくいっているのではないかと考えます。

この理解で大丈夫です。URLをネストしたいのが今回のタスクの意義で、コントローラーはroutesに合わせて良いです。

**Comment by shuma1020** [comment]
@ms2sato rewardsをネスト化するのがこのissueの目的だと思うのですが、下記のようにネスト化し、routesに出たものをパスをlink_toに載せるとエラーになってしまうということです。
```rb
resources :products do
    collection  do
      get'draft'
      get'release'
    end
    resources :rewards
  end
```

**Comment by ms2sato** [comment]
@shuma1020 PRの方へ回答しています。

**Comment by ms2sato** [comment]
別Issueを作成しました。再挑戦案件です。 https://github.com/shuma1020/training_app/issues/57
