### ISSUE TITLE
Product#owner?(user) の作成

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#80]
Productモデルにowner?(user) というメソッドを作成しましょう。

意味合いとしては `@product.user_id == current_user.id` の部分が `@product.owner?(current_user)` に置き換えられるものです。

また、現在のコードの中でこのメソッドで置き換えられる場所を変更してください。

**Comment by shuma1020** [comment]
@ms2sato 
owner?メソッドを調べたところあまりヒットしないことから、作成というのは自分で0から作るという認識でよろしいですか？

**Comment by ms2sato** [comment]
@shuma1020 

> Productモデルにowner?(user) というメソッドを作成しましょう。

この表現から、 「自分で0から作る」 と理解してくれると嬉しいです。

**Comment by shuma1020** [comment]
@ms2sato 
このようにしました！
```
def owner?(user)
        @product.user_id == current_user.id
    end
```

**Comment by ms2sato** [comment]
@shuma1020 終わっていたら commitして pushしてくださいな。動作確認もした上でお願いします。
