### ISSUE TITLE
[rails c] 抽出した複数のRewardをpriceの額の順の降順に並べて取得する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#82]
Reward.all で全てのRewardが取得できますが、この結果を price の値の順でソートしたいです。
SQLでは `order by` で行います。ただし、price の大きい順で取得します。

**Comment by shuma1020** [comment]
@ms2sato 
今回の場合、まずモデルを結合するのかと考えています。そこで調べてみたところincludesメソッドなどがそれに当たりそうです。

**Comment by ms2sato** [comment]
@shuma1020 申し訳ない。 price の順だったので書き直しました。テーブルは Rewardだけで完結するので includes などを利用する必要はない想定です。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！
```
Reward.order(price: :desc)
  Reward Load (14.3ms)  SELECT "rewards".* FROM "rewards" ORDER BY "rewards"."price" DESC LIMIT $1  [["LIMIT", 11]]
```

**Comment by ms2sato** [comment]
@shuma1020 OKです！
