### ISSUE TITLE
haml の Viewを導入する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#83]
一応インターンの中で、これを（おそらく結構な頻度で）やるはずなので、ちゃんとやれるようになって欲しいと聞いています。退屈な作業かもしれませんが、練習をちゃんと積まないといきなりできる方ではないと思うので、シッカリやります。

- [x] まず、Hamlとはどのようなものかを調べてください。このIssueの続きで書いてください。
- [x] Hamlと同じようなものだと理解できる名前を挙げてください。一つは答えられる想定です。
- [ ] ブランチを作って、Hamlを導入してみてください。
- [x] ViewをHaml形式に変換してください。

**Comment by shuma1020** [comment]
- 「HTMLを抽象化したマークアップ言語」。
HTML/XMLを生成する為のマークアップ言語で、
より短いコードで綺麗に簡潔にコードを書くことができる記法。
- erbでしょうか？

**Comment by ms2sato** [comment]
> erb でしょうか？

その観点だともう一つ挙げて欲しいです。Rails5実践入門で出てきています。

**Comment by shuma1020** [comment]
@ms2sato 
slimでしょうか？

**Comment by ms2sato** [comment]
@shuma1020 OKです！ erbの代わりとしてSlimやHamlを利用します。

TenantaさんはViewをHamlで書くので、その練習はキッチリやっておくと実際に仕事になった時に混乱しないで進められると思います。

Hamlを導入後、現在のerbをHamlに全部直します。この方法は一度調査をして効率の良い変換をしましょう。その上で画面をHamlで書く練習もします。

**Comment by shuma1020** [comment]
@ms2sato 
とりあえずproduct#indexをhamlに変えています。まとめて変えるやり方がありそうですが、練習のために行なっています！

**Comment by shuma1020** [comment]
@ms2sato こちらのissueは全てをhamlに変えて完了ですか？
products/indexはhamlになったのでご確認いただけると幸いです！

**Comment by ms2sato** [comment]
@shuma1020 いいですね。一回簡単な方法を素早く試して確認求めるのは仕事のやり方として適切です。

同じ要領で全ての画面に対応してください。
難しいものがあったら相談ください。

あと、自動変換されたものは良いと思いますが、内容を変更前と見比べてみて、どのように書き変わるのかは学習してください。今後手作業で自分で書いていくようになりますよ。

作業途中のファイルはpushせずに入ってしまったら消すようにしてください。チェックお願いします。

**Comment by shuma1020** [comment]
@ms2sato 
devise :userでできたもの以外は変換いたしました！

**Comment by ms2sato** [comment]
終わってるのでClose
