### ISSUE TITLE
「パトロンになる」機能の残項目（細かなもの）

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#85]
- products/show.html の color:red を付ける時にifの範囲が広すぎ
  - これ、解説必要ですか？ color: red を付けるだけのために大きな範囲をコピペされているので直すべきという話です。
- products/show.html の インデント を調整する
- reward のアクセス修飾子 をつける

**Comment by shuma1020** [comment]
@ms2sato 
- タイトルのみにしました
<td  style="color:red"><%= reward.title %></td>


**Comment by ms2sato** [comment]
@shuma1020 残念ながら私が伝えたかったことが伝わらなかったようです。

>  color: red を付けるだけのために大きな範囲をコピペされているので直すべき

https://github.com/shuma1020/training_app/blob/b1e8bf7c79b54a54a1a0db008043ad03efa5adc9/app/views/products/show.html.erb#L64-L96

この範囲で、下記のような内容が3回書かれています。これ、3回書かないとダメですか？**partialなどを利用せず** この範囲を1回で書く記述には出来ないのでしょうか。

安易にコピペしてコードを増やすのはよくない癖なので、指摘しています。

```
 <td><%= reward.title %></td> 
       <td><%= reward.description %></td> 
       <td><%= reward.price %></td> 
       <td><%= reward.product_id %></td> 
       <td><%= reward.user_id %></td> 
       <td><%= link_to 'Show', mypage_product_reward_path(@product, reward) %></td> 
       <td><%= link_to 'Edit', edit_mypage_product_reward_path(@product, reward) %></td> 
       <td><%= link_to 'Destroy', mypage_product_reward_path(@product, reward), method: :delete, data: { confirm: 'Are you sure?' } %></td> 
 ```

**Comment by shuma1020** [comment]
@ms2sato 
訂正しましたので確認お願いします！

**Comment by ms2sato** [comment]
@shuma1020 いい感じになってました！

ちなみに、以下のような書き方（ちょっとタグの関係が不自然に見えますが）もありますよ。
```
<td <% if @patron && reward == @patron.reward %>style="color:red"<% end %> ><%= reward.title %></td>
```
