### ISSUE TITLE
Patronの `validate :donation_error, if: :donation_check` が冗長

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#86]
`validate` の donation_error の中で if 文を書いてしまうのが良いと思います。というのも donation_errorが単純にエラーメッセージを入れるだけになっていて、二つのメソッドに分ける必要性が薄い為です。

**Comment by shuma1020** [comment]
@ms2sato 
falseのところを無くしてみました！
```
def donation_check
    if self.donation != nil
      reward = product.rewards.order(price: :desc).last
      self.donation < reward.price
    end
  end
```

**Comment by ms2sato** [comment]
@shuma1020 私の日本語を正しく捉えていただいていないようです。

- donation_error の中で if 文を書いてしまうのが良い
- 二つのメソッドに分ける必要性が薄い

この二つの文章から提示してくれた内容になりそうに思えないのですが、御一考されたし。

**Comment by ms2sato** [comment]
@shuma1020 コード見ました。Very Good! 
文章丁寧に読んでいくようにしてくれるとトータルコストが減るので心がけてくだされ。

**Comment by shuma1020** [comment]
@ms2sato はい！
