### ISSUE TITLE
[手が空いたら]PatronsController#create のロジックを モデルへ移動する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#87]
多分この言葉だけでいきなり手を動かしても難しいと思うので、イメージ合わせをしてからです。もしも手を付ける時には先に「どういう範囲をどのモデルにどんなメソッド名で」移動するかを相談してから進めます。

**Comment by shuma1020** [comment]
@ms2sato 
この範囲ではないかなと考えていますが、どのように行うかはまだ検討中です。
```rb
 @rewards = Reward.where("price<?",@patron.donation)
```

**Comment by ms2sato** [comment]
@shuma1020 移動する範囲は、以下の条件です。下記の言葉で判断するのが難しいと思っていて、なので手が空いたらとしています。やるとして次回の対面あたりで会話だと思います。

- WEBに関係しないこと（paramsを渡すことは許しますが、それ以外のWEB要素が入ることは基本的にありません）
- なるべく多くのロジックの範囲を含むこと

**Comment by ms2sato** [comment]
LGTM
