### ISSUE TITLE
Product#status に enumを導入する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#9]
https://github.com/shuma1020/training_app/issues/5

この知識を使って
statusに属性を作りましょう。 まずは以下くらいがいいと思います。

- 0: 下書き
- 1: 公開

**Comment by ms2sato** [comment]
@shuma1020 DONEになってますが、コードどこに入ってますか？pushしてからアサインくれると嬉しいでーす。

**Comment by shuma1020** [comment]
承知しました！

**Comment by ms2sato** [comment]
ちなみに、git のコミットを 作業単位にする、というのが現場でやることなので、こういう細々したIssueの時は、このIssueの内容だけでコミットしちゃうと良いですよ。

ブランチを活用し出すともう少し色々あるんですが、今は1コミット1作業くらいの感覚で良いです。
質問したい時は途中でもcommitしてpushして大丈夫です。

**Comment by ms2sato** [comment]
@shuma1020 
ちなみに、git のコミットを 作業単位にする、というのが現場でやることなので、こういう細々したIssueの時は、このIssueの内容だけでコミットしちゃうと良いですよ。

ブランチを活用し出すともう少し色々あるんですが、今は1コミット1作業くらいの感覚で良いです。
質問したい時は途中でもcommitしてpushして大丈夫です。

**Comment by ms2sato** [comment]
@shuma1020 まず、下記の書き方はしないです。私が例示していたのは意味合いなので、日本語で指定はしないんですよ。アルファベット当ててください（名前は考えてください）
https://github.com/shuma1020/training_app/blob/master/app/models/product.rb#L8

**Comment by shuma1020** [comment]
@ms2sato なるほど、わかりました！

**Comment by ms2sato** [comment]
LGTM!
