### ISSUE TITLE
[調査]DBの制約について調べる

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#90]
DBには制約という機能があります。これについて調べてまとめてください。堅牢なアプリケーションを作るには大事な知識です。

**Comment by shuma1020** [comment]
@ms2sato 
下記の制約がある。データベースに新たなテーブルを作成するときに使用する時に発行するSQL　のCREATE TABLEに制約をかける。
- NOT NULL制約
- チェック制約
- 一意性制約（UNIQUE KEY)
- 主キー制約 (PRIMARY KEY)
- 参照整合性制約、外部キー制約 (FOREIGN KEY)
[参考](https://qiita.com/Uejun/items/de02b78adbc54868d40d)

**Comment by ms2sato** [comment]
@shuma1020 お、良いですね。Railsでは マイグレーション時に指定するのですが「こんな風にしていする」というサンプルをこのIssue上に貼ったりできますか？

**Comment by shuma1020** [comment]
@ms2sato 
サンプルです！

```rb
class ChangeColumnToUser< ActiveRecord::Migration

  
  def up
    change_column :users, :uuid, :string, null: false, default: 0
  end


  def down
    change_column :users, :uuid, :string, null: true, default: 0
  end
end
```

```rb
def up
    add_column :cards, :progress_status, :integer, null: false

    execute <<-SQL
      ALTER TABLE cards
        ADD CONSTRAINT status_limitation
        CHECK (progress_status >= 0 AND progress_status <= 2);
    SQL
  end
```
```rb
add_index :xxxs, :yyy_id, unique: true
```

**Comment by ms2sato** [comment]
@shuma1020 概ね大丈夫かな？変更の時は書いてくれたようにやります。同様にcreate_table の時にも指定できるのでできるようになると良いでしょう。

 execute している `CHECK (progress_status >= 0 AND progress_status <= 2);` はあまり利用しないのでその旨承知しておいてください。値の範囲指定はRailsのバリデーションで対応する事が多いです。

**Comment by ms2sato** [comment]
概ね大丈夫そうなのでClose
