### ISSUE TITLE
[調査]SQLのJOINについて調べる

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#91]
SQLにはJOINという機能があります。これがどういう道具なのか調べましょう。

**Comment by shuma1020** [comment]
@ms2sato 
テーブル同士を結合するもの。２つのテーブルを結合する方法として、大きく内部結合と外部結合というものが存在する。内部結合は、それぞれのテーブルの指定したカラムの値が一致するものだけを結合します。外部結合は、内部結合のようにそれぞれのテーブルの指定したカラムの値が一致するものを結合するのに加え、どちらかのテーブルにしか存在しないものに関しても取得します。

参考記事
https://qiita.com/naoki_mochizuki/items/3fda1ad6594c11d7b43c
https://www.sejuku.net/blog/73650

**Comment by ms2sato** [comment]
@shuma1020 ActiveRecordにjoinに相当するメソッドがあります。それを使って rails c で何か情報を取り出したりしてみてください。JOINの効果がわかりそうな内容を自分で考えられるととても良いです。

**Comment by shuma1020** [comment]
@ms2sato 
下記の解釈は、patrons.product_id= "products.idの条件の素で２つのproductテーブルとpatronテーブルを引っ付ける。
```rb
product_patrons = Product.joins(:funders)
  Product Load (0.9ms)  SELECT "products".* FROM "products" INNER JOIN "patrons" ON "patrons"."product_id" = "products"."id" INNER JOIN "users" ON "users"."id" = "patrons"."user_id" LIMIT $1 
```
引っ付けたテーブル(ProductテーブルとPatronテーブルが結合している)からPatronを出力
```rb
product_patrons.each do |product_patron|
irb(main):042:1* product_patron.patrons
irb(main):043:1> end
```

**Comment by ms2sato** [comment]
@shuma1020 書いてあることは概ね良さそうですが、本質が掴みにくいと思うので、JOINを活用して以下をやってみてください。

「"100円以上のdonationをしてくれているpatronがいる"Productを全て取得する」

**Comment by shuma1020** [comment]
@ms2sato 

```rb
products = Product.joins(:patrons).where("donation>=?",100)
products.each do |product|
  p product.patrons
 end
```

**Comment by ms2sato** [comment]
@shuma1020 これで「今まで Product のカラムだけ検索していたけれども、関連するテーブルのカラムを条件に検索もできる」という差異に気付けていると良いのですが、今後活用できそうですか？

**Comment by shuma1020** [comment]
@ms2sato 
つまり今回の場合Productモデルをdonationの条件を指定して絞り込むことができるということですね！

**Comment by ms2sato** [comment]
@shuma1020 OKです。一旦Closeします。
