### ISSUE TITLE
通知のアイコンと未読数のデザインを調整する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#92]
![image](https://user-images.githubusercontent.com/627817/72981389-fe534600-3e1f-11ea-8479-ed3a4dea408b.png)

**Comment by shuma1020** [comment]
<img width="108" alt="スクリーンショット 2020-01-24 15 18 06" src="https://user-images.githubusercontent.com/56459339/73048506-c0582f80-3ebc-11ea-831c-0f542856a6e1.png">

**Comment by ms2sato** [comment]
LGTM
