### ISSUE TITLE
DBの制約を入れる

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#94]
https://github.com/shuma1020/training_app/issues/90
の知識を利用して、今のサービスにDB制約を入れましょう。下記あたりを特に指定する事が多いです。

- null:false
- default
- unique（複合uniqueも含めて）

**Comment by shuma1020** [comment]
@ms2sato 
ブランチtransactionにて修正しました！

**Comment by ms2sato** [comment]
OKです！
