### ISSUE TITLE
products#indexとshowのbackground-imageをうまく調整する

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/training_app#96]
@ms2sato 
layoutブランチより

> よく考えたらbackground-imageは使ったことありました！ただその時は静的な画像を入れていました。今回は動的な画像を入れないといけないので、html上で指定するのが良いのかと思い下記のようなイメージで描こうとしているのですが、なかなか苦戦しています。

```
.background-image{style: 'background-image:url(product.image.url)'}
```

**Comment by ms2sato** [comment]
@shuma1020 `.background-image` は独自に作成したクラス名ですよね（これはわかりにくいと思うから名前変えた方が良いとは思う）。方向としてはそんなに間違えていないと思いますよ。画面側でURLを指定しないとやりづらいですからね。

**Comment by shuma1020** [comment]
@ms2sato 
クラス名はcard-imageに修正してみました！もう一工夫してみます！

**Comment by ms2sato** [comment]
@shuma1020 ヒント:  `product.image.url` が反映されなくて困っていると思います。 ERBだったらどう書くかができれば http://htmltohaml.com/ などでどう変換できるかがわかると思います。

もしくは「文字列の中に、rubyのコードの結果を入れる方法」を理解するかでしょうか。

**Comment by shuma1020** [comment]
@ms2sato 
下記のように画像を指定した場合も表示されないことから書き方が、そもそものbackgroung-image書き方がよくないのかと

```
.card-image{style:'background-image:url("/uploads/product/image/7/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88_2019-12-27_22.01.14.png")'}
```

**Comment by ms2sato** [comment]
@shuma1020 良い考えですね。その状態でChromeの開発者ツールでどうなっているか確認すると良い気がします。.card-imageの要素にどんなCSSが当たっているか確認できるはずです。

**Comment by ms2sato** [comment]
ちなみに、今やっている「とりあえず動かせそうな形から入る」は課題解決にとても良い手法なのでそのアプローチを覚えておいて様々なシーンで応用効かせてください。

**Comment by shuma1020** [comment]
@ms2sato 
card-imageを見直し、指定した画像を入れたら出力されました。そのことから文字列におけるrubyの書き方が間違っているのかと思います。

```rb
.card-image.border-bottom{style:'background-image:url("#{product.image.url}")'}
```

```rb
.card-image.border-bottom{style:'background-image:url("=product.image.url")'}
```

**Comment by ms2sato** [comment]
@shuma1020 
http://haml.info/tutorial.html
こういうの眺めるとそれっぽいのが見つかるかもですね。基本をチェックしに行くのは重要っす。

**Comment by shuma1020** [comment]
@ms2sato 
ありがとうございます！参考にして、こんな感じになって少し出力前と変わったのですが、url以降が全く表示されない感じです。hamlの書き方はあっていと思うので、他に原因がないか探しています。
```
.card-image.border-bottom{style:"background-image:url#{product.image.url}"}
```

**Comment by ms2sato** [comment]
できたのでClose
