### ISSUE TITLE
Products#indexにて表示するページを5枚でにする

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/training_app#97]
@ms2sato 
下記のページを実装する
<img width="1399" alt="スクリーンショット 2020-01-31 21 12 14" src="https://user-images.githubusercontent.com/56459339/73538470-78ae4680-446e-11ea-8cbc-e22dd23b1fb1.png">

**Comment by shuma1020** [comment]
@ms2sato 
動的なページを作るにはreactやjqが必要になると思いますが、まだ触れない方が良いですか？reactは勉強したことがあります。

**Comment by shuma1020** [comment]
@ms2sato 
kaminari-bootstrapというgemでpaginationを作ったのですが、gemを入れればbootstrapが適応されると書いてあったのですが普通のkaminariと変わりません。
https://wonderwall.hatenablog.com/entry/2015/08/09/094130

**Comment by ms2sato** [comment]
@shuma1020 まだ動的なところに手は出さないでOKです。やるときには jQueryからやると思う。Reactはまだまだ先。

**Comment by ms2sato** [comment]
@shuma1020 ページネートはあとでコメントします。

**Comment by ms2sato** [comment]
@shuma1020 https://github.com/mcasimir/kaminari-bootstrap ここが配布元だと思いますが、かなり古いですね。 bootstraap3までしか対応していない様子なので、別の方法を調べる方が良いと思います。本家でその辺りもサポートがあるので調べてみると良いでしょう。

**Comment by shuma1020** [comment]
@ms2sato 承知しました！ありがとうございます！

**Comment by ms2sato** [comment]
GJ!
