### ISSUE TITLE
Mypage::Product#indexを整える

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/training_app#98]
@ms2sato 
右のdropdownを押しても何も変化しないのはbootstrapが正しく機能/指定できていないからであると考えた方がいいですか？ただDropdown自体は出現しているため他の可能性(js)も考えられるのかと思います。
<img width="496" alt="スクリーンショット 2020-02-01 10 42 47" src="https://user-images.githubusercontent.com/56459339/73584985-ffe7d280-44df-11ea-8bd0-aeb290bbed24.png">

**Comment by ms2sato** [comment]
@shuma1020 ドロップダウンされる中身のHTMLがbootstrapのルール通りに出ているかは確認が必須です。多分これJS関係ないです。
